### ISSUE TITLE
Create a TCK

### ISSUE THREAD

**Issue by arthurdm** [eclipse/microprofile-open-api#13]
We'll need a TCK for this specification.  It should exercises the different parts of the spec.

**Comment by mrglavas** [comment]
@arthurdm I'm currently working on the skeleton for the TCK. Can you assign this one to me? Thanks.

**Comment by arthurdm** [comment]
Unfortunately the `Assignee` field only picks from the committers list, so can't assign.  But it's recorded here that @mrglavas is currently working on this issue.

**Comment by mrglavas** [comment]
Breakdown of TCK test scenarios:

API:
 - Direct testing of model construction through OASFactory.
 - Check that each method on model interfaces can be executed. 
 - Check that each getter method on model returns what was set with setter or builder method.
 - Test any other factory method that gets added for filtering, etc...
 - Negative testing for bad input (e.g. non-model interface passed to OASFactory.createObject()).
 
REST endpoints:
 - Test driver which accesses OpenAPI document endpoint and verifies that it returns the correct output.
 - Test query parameters on the endpoint (e.g. format = json, format = yaml)
 - Develop input for the test driver that covers all of the various documentation mechanisms.
  - Configuration values for mp.openapi namespace
  - OASModelReader
  - OASFilter
  - Static OpenAPI file (YAML / JSON)
  - Annotated JAX-RS applications
  
Utilities:
 - May require an OpenAPI parser to help with comparing expected output

**Comment by mrglavas** [comment]
I am currently working on the model construction test.

**Comment by arthurdm** [comment]
Looks good @mrglavas !    My only comment is that the query parameter (format) is an optional part of the spec, so the TCK should be testing with the `Accept` header (application/yaml and application/json).

**Comment by mrglavas** [comment]
Thanks @arthurdm. I've updated the description.

**Comment by arthurdm** [comment]
Closing this as we have other issues to handle the remaining TCK portions
