### ISSUE TITLE
Define endpoint to retrieve OpenAPI document

### ISSUE THREAD

**Issue by arthurdm** [eclipse/microprofile-open-api#14]
This spec needs to define an endpoint that will return the OpenAPI document that was generated from the processing of the annotations + models.  

I propose that the endpoint be `/openapi`, with a default Content-type of `application/yaml` but also supporting `application/json` Content requests.

This would mean that any implementation of MP OpenAPI would expose this endpoint.

**Comment by arthurdm** [comment]
Another consideration is to have a query param (something like `format=json`) to allow the format to change without having to use a REST client like POSTMAN

**Comment by arthurdm** [comment]
Another question for this design is: what happens when there's more than 1 application in that MP runtime?  

I propose we follow a similar convention started by the MicroProfile HeathCheck specification:

```
The 1.0 version of the MP-HC specification does not define how the /health endpoint may be partitioned in the event that the MicroProfile runtime supports deployment of multiple applications. If an implementation wishes to support multiple applications within a MicroProfile runtime, the semantics of the /health endpoint are expected to be the logical AND of all the application in the runtime.
```

This means that the MP OpenAPI specification will not define exactly the semantics of a multiple app environment, but a reasonable expectation is that an implementation that support multiple apps would aggregate the various OpenAPI documents into a single valid document (taking care of renaming conflicting IDs, merging, etc).

**Comment by Emily-Jiang** [comment]
+1

**Comment by arthurdm** [comment]
Resolved in https://github.com/eclipse/microprofile-open-api/pull/40
