### ISSUE TITLE
@Schema maximum and minimum are Strings?

### ISSUE THREAD

**Issue by EricWittmann** [eclipse/microprofile-open-api#178]
For example, the `@Schema` annotation has this property:

https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/annotations/media/Schema.java#L113-L119

```
    /**
     * Sets the maximum numeric value for a property. 
     * Ignored if the value is an empty string.
     * 
     * @return the maximum value for this schema
     **/
    String maximum() default "";
```

The data model defines these properties as `BigDecimal`.  Can I assume that this is done because java annotations don't support `BigDecimal` as a type for a property and that no other type would be sufficient?

**Comment by EricWittmann** [comment]
Note that the `Schema` model also has the property `multipleOf` which required a BigDecimal, but the corresponding property of the annotation is `double`.

**Comment by msavy** [comment]
Just a quick thought: could Hibernate's `@Size` annotation serve as some inspiration? It has a variety of properties that allow you to constrain in a variety of ways, such as `@Digits(integer=10, fraction=2)`.

**Comment by EricWittmann** [comment]
Assigning to myself. :)

**Comment by EricWittmann** [comment]
OK so the reason that these properties are String instead of something more (seemingly) sensible (e.g. double) is that there is no default value that we could use to clearly indicate that the property was not included.  In other words, if we made the property a `double` then there is no default value we could provide that is not also a valid value.

The way all these annotation properties work is that every one of them has a default value.  When the annotation processor reads them, if the default value is found (for any given annotation property) then the processor is supposed to **not include it** in the final OAI document being generated.  For `String` properties, the default value is typically empty string.  So when the processor reads that property and sees empty string, it skips it.

For this particular property, switching to `double` would mean there is no sensible default that could indicate "skip it" to the processor.

We **could** do something like `@Digits` as @msavy suggests.  I think that would allow us to use `null` as the "skip it" indicator.  But it adds a fair bit of complexity for rather little value.

So for now I think we should update the javadoc to explain why the type is String and then close this issue.
