### ISSUE TITLE
Define way of providing extra vendor specific configuration 

### ISSUE THREAD

**Issue by arturdzm** [eclipse/microprofile-open-api#18]
Define a common way to provide extra properties for different vendors using MicroProfile config
For example:

openapi.extension = { myExt: myValue}
or
openapi.extension.myExt = myValue

**Comment by arturdzm** [comment]
Best practices for defining vendor extensions:

microprofile.openapi.extensions.ext1 = value
microprofile.openapi.extensions.ext1 = [value1, value2]

**Comment by leochr** [comment]
this will be covered by #8 - so this issue can be closed.

**Comment by arthurdm** [comment]
Closing via merge #48
