### ISSUE TITLE
Invalid assertions in AirlinesAppTest.testExampleObject()

### ISSUE THREAD

**Issue by EricWittmann** [eclipse/microprofile-open-api#184]
In the `AirlinesAppTest` there is a method called `testExampleObject` with [the following two assertions](https://github.com/eclipse/microprofile-open-api/blob/master/tck/src/main/java/org/eclipse/microprofile/openapi/tck/AirlinesAppTest.java#L658-L662):

```java
// Example in Content
vr.body("paths.'/reviews/{user}'.parameters.find{ it.name=='user'}.content.examples.value", hasItem("bsmith"));

// Example in Parameter
vr.body("paths.'/reviews/{user}'.parameters.find{ it.name=='user'}.examples.value", hasItems("bsmith", "pat@example.com"));
```

I don't think either of these paths are possible in OAI 3.  For one thing, a `Content` object in OAI is always a map of `MediaType` objects.  As a result, the content property in the first assertion would not have an `examples` property.  It should instead be a map of media types.  The examples can then be found in the media type object.

I also don't think that `value` is a valid property for examples in this context.  It suggest that `value` is a property of the `examples` object.  But `examples` I think is a map of `Example` objects, so it seems there should be something else in there.

I've run out of steam today - I'll try to come up with what I think the resulting OAI JSON (or yaml) should be given the test classes.  I believe the assertion is trying to test [the following test app code](https://github.com/eclipse/microprofile-open-api/blob/master/tck/src/main/java/org/eclipse/microprofile/openapi/apps/airlines/resources/ReviewResource.java#L221-L229):

```java
@Parameter(
      name = "user",
      description = "username of the user for the reviews",
      required = true,
      in = ParameterIn.PATH,
      content = @Content(
          examples = @ExampleObject(
              value = "bsmith")),
      examples = { @ExampleObject("bsmith"), @ExampleObject("pat@example.com")})
```

**Comment by EricWittmann** [comment]
OK, I had some time to put together valid OAI markup for this.  Here it is:

```
{
    "name": "user",
    "description": "username of the user for the reviews",
    "required": true,
    "in": "path",
    "content": {
        "MEDIA_TYPE" : {
            "EXAMPLE_NAME": {
                "value": "bsmith"
            }
        }
    }
}
```

The problem is that the `Content` must have a media type and the `Example` must have a name.  See the two properties in all-caps.  In the above TCK `@Parameter` code, what should those two values be?  My current implementation doesn't generate anything past the `Content` object because of the missing names (media type and example name).

**Comment by arthurdm** [comment]
Ya, I think there's an issue in that assertion.  

Here's a sample output right from the OAS3 spec:

```
  "content": {
    "application/json": {
      "examples": {
          "user" : {
            "summary": "User Example", 
            "externalValue": "http://foo.bar/examples/user-example.json"
          } 
        }
```
Some open question would be:
- what is the default media type if `@Consumes` is not specified?   Should it be `*/*`? 
- what is the default example name?   maybe `name` is required?

**Comment by EricWittmann** [comment]
Yes, those are the open questions!  Exactly.  :)

I also +1 both of your suggested solutions.

**Comment by arthurdm** [comment]
merged
