### ISSUE TITLE
Liberty-specific assertion in OASConfigScanDisableTest

### ISSUE THREAD

**Issue by EricWittmann** [eclipse/microprofile-open-api#187]
[The following code](https://github.com/eclipse/microprofile-open-api/blob/master/tck/src/main/java/org/eclipse/microprofile/openapi/tck/OASConfigScanDisableTest.java#L43-L50) can be found in the **OASConfigScanDisableTest** test:

```java
    @RunAsClient
    @Test(dataProvider = "formatProvider")
    public void testScanDisable(String type) throws InterruptedException {
        vr = callEndpoint(type);
        vr.body("openapi", equalTo("3.0.0"));
        vr.body("info.title", equalTo("Liberty APIs"));
        vr.body("info.version", equalTo("1.0"));
        vr.body("paths", aMapWithSize(0));
        
    }
```

I suggest only asserting on the openapi version (and even then looking for 3.0.x rather than 3.0.0) and the paths.  Perhaps also check for empty/missing components, servers, tags, etc?

**Comment by arthurdm** [comment]
merged.
