### ISSUE TITLE
Update server configurations tests

### ISSUE THREAD

**Issue by leochr** [eclipse/microprofile-open-api#195]
The [server configurations](https://github.com/eclipse/microprofile-open-api/blob/master/tck/src/main/resources/server-microprofile-config.properties) and the [tests](https://github.com/eclipse/microprofile-open-api/blob/8f8888bb161594a67b1e99bbb4064cc52514d95b/tck/src/main/java/org/eclipse/microprofile/openapi/tck/OASConfigServersTest.java#L45) don't match.

Also, adding some additional checks to ensure that the processing of servers configuration is correct.

**Comment by arthurdm** [comment]
merged via #196
