### ISSUE TITLE
TCK test ModelReaderAppTest has an unused method: testAvailabilityGetParamater

### ISSUE THREAD

**Issue by EricWittmann** [eclipse/microprofile-open-api#197]

**Comment by arthurdm** [comment]
@leochr

**Comment by leochr** [comment]
Checked with Anna Safonov who authored the ModelReaderAppTest and she believes that the test is missing the annotation tags. It's meant to test the construction of Parameters via programming models. Anna will make the necessary changes, verify that the test is correct/passes and make a PR.

**Comment by EricWittmann** [comment]
For reference:  https://github.com/eclipse/microprofile-open-api/blob/master/tck/src/main/java/org/eclipse/microprofile/openapi/tck/ModelReaderAppTest.java#L156-L183

**Comment by arthurdm** [comment]
Fixed by PR #202
