### ISSUE TITLE
@Schema.implementation -> $ref should be vendor specific

### ISSUE THREAD

**Issue by EricWittmann** [eclipse/microprofile-open-api#198]
Several TCK tests assume that the following annotation will result in a $ref in the OAI document:

```
@Schema(
    implementation=BeanClass.class
)
```

For a variety of reasons discussed on yesterday's call, we have decided that the TCK should not require vendors to create a reference in the above case.  It's acceptable for a vendor to instead inline the schema definition.

For this reason, we should change the TCK apps to use `ref` instead of `implementation` if we really want to test references.

**Comment by arthurdm** [comment]
Closed by PR #199

**Comment by EricWittmann** [comment]
PR 199 closed issue 198!  SOOOO close!
