### ISSUE TITLE
TCK: Change the way additional artifacts are added to the test deployment

### ISSUE THREAD

**Issue by mkouba** [eclipse/microprofile-open-api#201]
TCK should not require additional artifacts in the lib dir of the runner project. Instead, [ShrinkWrap Maven Resolver](https://github.com/shrinkwrap/resolver) could be used so that the tck runner does not have to manage the dependencies, versions, etc.

**Comment by arthurdm** [comment]
@navidsh - I think you were looking into this as well?

**Comment by navidsh** [comment]
@mkouba we are looking Maven Resolver to handle that. We'll create a PR to fix this.

**Comment by mkouba** [comment]
That's great. Thanks.

**Comment by mkouba** [comment]
Actually, it seems this change is not necessary if we manage to fix #203.

**Comment by arthurdm** [comment]
Thanks guys.  Closing this as #203 was closed.  Thanks again for the contribution @mkouba
