### ISSUE TITLE
TCK: There is no need to deploy additional proxy.war

### ISSUE THREAD

**Issue by mkouba** [eclipse/microprofile-open-api#203]
`AppTestBase` currently deploys an additional `proxy.war` for each tck test. This implies that the target Arquillian container **must support** multiple deployments. However, it seems that the only purpose of this deployment is to convert YAML to JSON. I believe that this could be handled on the client side and thus the "proxy" deployment is not necessary. The logic from `YamlToJsonConverterServlet` should be probably moved to `AppTestBase`.

**Comment by EricWittmann** [comment]
Yeah I noticed that as well (the proxy servlet) but didn't realize it was a separate deployment.  +1 to this sentiment.  No reason it can't be converted client-side assuming rest assured has some hooks.

**Comment by arthurdm** [comment]
@navidsh - thoughts on this?

**Comment by mkouba** [comment]
It seems that `io.restassured.filter.Filter` together with `io.restassured.builder.ResponseBuilder` could be used to perform the conversion? I can try to send a PR if needed.

**Comment by navidsh** [comment]
I looked into the rest assured javadoc and couldn't find a way to add a new parser. Looks like it only works with a couple of [predefined parsers](http://static.javadoc.io/io.rest-assured/rest-assured/3.0.2/io/restassured/RestAssured.html) and YAML isn't one of the [parsers](http://static.javadoc.io/io.rest-assured/rest-assured/3.0.2/io/restassured/parsing/Parser.html):

> REST Assured providers predefined parsers for e.g. HTML, XML and JSON. But you can parse other kinds of content by registering **a predefined parser** for unsupported content-types by using: `RestAssured.registerParser(<content-type>, <parser>);`
 
But it looks like a `Filter` could be promising 👍 . Can you please send a PR for this change to remove the proxy.war across the TCK?

**Comment by mkouba** [comment]
I'll try to send a PR tomorrow.
