### ISSUE TITLE
The TCK airlines application should produce a valid OpenAPI document.

### ISSUE THREAD

**Issue by mrglavas** [eclipse/microprofile-open-api#209]
Loading the TCK airlines application and running it through OpenLiberty's validator produced the following errors:

- Message: Required "scopes" field is missing or is set to an invalid value, Location: `#/components/securitySchemes/reviewoauth2/flows/authorizationCode`
 - Message: Required "scopes" field is missing or is set to an invalid value, Location: `#/components/securitySchemes/reviewoauth2/flows/password`
 - Message: The encoding property specified cannot be validated because the corresponding schema property is null, Location: `#/paths/~1user~1createWithArray/post/requestBody/content/application~1json`
 - Message: The Path Item Object must contain a valid path. The "GET" operation of the "/user/{username}" path does not define a path parameter that is declared: "username", Location: `#/paths/~1user~1{username}`
 - Message: The Link Object specified an "operationId" field with "getUserByName" value which points to an Operation Object that does not exist, Location: `#/components/links/UserName`
 - Message: The Link Object specified an "operationId" field with "getUserByName" value which points to an Operation Object that does not exist, Location: `#/paths/~1user~1{id}/get/responses/200/links/User name`

**Comment by mrglavas** [comment]
Should verify whether these errors are legitimate by checking the constraints in the OpenAPI specification and then fix them.

**Comment by arthurdm** [comment]
thanks @Rachelwrq

**Comment by arthurdm** [comment]
fixed via PR #315 - thanks @Rachelwrq!
