### ISSUE TITLE
Add package documentation for the OpenAPI model.

### ISSUE THREAD

**Issue by mrglavas** [eclipse/microprofile-open-api#210]
There should be package level documentation for the OpenAPI model which describes its purpose and usage. It should probably also clearly state that the behaviour of methods inherited from java.lang.Object are undefined by the MicroProfile OpenAPI specification.

**Comment by arthurdm** [comment]
Thanks @mrglavas - definitely we should fix this.  I wonder if this particular case is covered by https://github.com/eclipse/microprofile-open-api/issues/175?

**Comment by mrglavas** [comment]
@arthurdm Yes, would fit underneath the broader work item.

**Comment by arthurdm** [comment]
Sounds good.  I added this comment into #175, so will close this item so that we have a single place to track this.
