### ISSUE TITLE
Support EE8 / JAX-RS 2.1

### ISSUE THREAD

**Issue by arthurdm** [eclipse/microprofile-open-api#214]
This item will investigate what changes are required to the spec in order to claim support for EE8, in specific for JAX-RS 2.1.  

The changes to this spec should be backwards compatible with our current EE7 / JAX-RS 2.0 version.  

One of the more interesting aspects from JAX-RS 2.1 is the concept of a server-sent events, which can potentially map to callbacks.

**Comment by arthurdm** [comment]
We should also add support for `Patch`: https://javaee.github.io/javaee-spec/javadocs/javax/ws/rs/PATCH.html

**Comment by arthurdm** [comment]
Also - we should define in the spec the JAX-RS annotations that we support and what OAS3 elements they map into.  Most of this is common knowledge, but it should be in the spec.

**Comment by arthurdm** [comment]
Discussed on Sept 10 hangout to split this into 2 issues:  smaller changes, such as Patch for `1.1`, and bigger changes such as SSE / Callbacks for `2.0`

**Comment by MikeEdgar** [comment]
The current specification versions for Jakarta EE and JAX-RS should be evaluated for any features that may relate to MP OpenAPI. New issues will be opened for specific features that may/should be implemented in this spec.
