### ISSUE TITLE
Update wiki with samples

### ISSUE THREAD

**Issue by arthurdm** [eclipse/microprofile-open-api#215]
We currently have a [wiki](https://github.com/eclipse/microprofile-open-api/wiki) with an empty skeleton:

- [x] Annotation Samples
- [x] OASModelReader Samples
- [x] OASFilter Samples
- [x] Static File Samples
- [x] Configuration Samples

This workitem will track the completion of these sub pages.

**Comment by arthurdm** [comment]
@a-saf will be working on this.

**Comment by janamanoharan** [comment]
Here are the samples for OASFilter:
[OASFilter-Samples.md.zip](https://github.com/eclipse/microprofile-open-api/files/2049911/OASFilter-Samples.md.zip)

**Comment by arthurdm** [comment]
thanks @janamanoharan - merged: https://github.com/eclipse/microprofile-open-api/wiki/OASFilter-Samples

**Comment by arthurdm** [comment]
merged @a-saf's changes to https://github.com/eclipse/microprofile-open-api/wiki/OASModelReader-Samples

**Comment by janamanoharan** [comment]
Here are the samples for the configuration samples:
https://github.com/janamanoharan/microprofile-open-api/wiki/Configuration-Samples

**Comment by arthurdm** [comment]
thanks @janamanoharan - I merged it: https://github.com/eclipse/microprofile-open-api/wiki/Configuration-Samples

I updated the checkboxes at the first comment

**Comment by wojtczat** [comment]
Here are the samples for the annotations
https://github.com/wojtczat/microprofile-open-api/wiki

**Comment by Rachelwrq** [comment]
Here are the samples for the static files
https://github.com/Rachelwrq/microprofile-open-api/wiki

**Comment by arthurdm** [comment]
thanks @wojtczat and @Rachelwrq !   

This concludes the wiki, great job everyone!
