### ISSUE TITLE
Support singular example in Content annotation

### ISSUE THREAD

**Issue by arthurdm** [eclipse/microprofile-open-api#216]
At the moment our `@Content` annotation only supports an array of `ExampleObject`, however, our `Content` **model** correctly supports both the array and the single `example`, as per the OAS3 spec.  

This workitem will include the single example inside the `@Content` annotation, so that a simple / single example can be given without affecting the underlying `@Schema`, since it could be referenced from different places.

We should add a corresponding TCK test too.

**Comment by EricWittmann** [comment]
I can take this one.

**Comment by ivanjunckes** [comment]
Hi Arthur, I was taking a look at this today and I probably didn't quite understand the description.

These are the references to the example object I found. All of them are using arrays and they support one value as well.
![image](https://user-images.githubusercontent.com/2260551/41824639-eb20ff3a-77e9-11e8-8c47-6b42f660eb47.png)

Not sure I get when you say it only supports array. I am probably missing something, could you please point to the code so I can better understand?

Thanks.

**Comment by arthurdm** [comment]
Hey @ivanjunckes - Currently the `@Content` annotation just support this: https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/annotations/media/Content.java#L47

So we need to add an additional method with the signature `String example();`, such as done in here: https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/annotations/media/Schema.java#L265

**Comment by arthurdm** [comment]
Closing - finished in PR #239
