### ISSUE TITLE
Deprecate [war root]/META-INF location

### ISSUE THREAD

**Issue by arjantijms** [eclipse/microprofile-open-api#222]
MP Open API currently specifies `[war root]/META-INF` for certain files to be placed as well as a MP Config properties file.

`[war root]/META-INF` is however a highly unusual location, and doesn't align with any existing conventions in either MicroProfile, Java EE, or related technologies.

In fact, the usage of this folder is so alien for war archives that I think we should consider it to be a spec bug and therefor should best deprecate it.

I'd like to propose to use the `[war root]/WEB-INF` folder for the MP Open API specific files, and **do not** put any requirements on the configuration file used by MP Config (just specify the properties, but leave it to MP Config where they ultimately originate from)

**Comment by arthurdm** [comment]
Closing as dup of https://github.com/eclipse/microprofile-open-api/issues/221#issuecomment-390417274
