### ISSUE TITLE
Package OASFactoryResolver into an SPI artifact

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile-open-api#224]
This method seems to be an implementation leak. OSGi is able to use SPI today (with spy fly) so no need of it.

**Comment by arthurdm** [comment]
hey @rmannibucau - that method helps vendors remains flexible with their implementation of the spec.  If a particular vendor doesn't need to set the method, that's totally fine, but I wouldn't want to break backwards compatibility with the spec just to remove it.

**Comment by rmannibucau** [comment]
Then it must be forbidden to change it once it was set otherwise - currently - it is not thread safe and leads to easy to get bugs :(. This is why removing it is fine IMO since it is not usable already ATM. Vendors don't need it anyway for their impl since the SPI will be supported (with a service loader or not) in all environments (vendors are used to switch the API for such needs which avoid to pollute the user API space with methods they can't use).

**Comment by arthurdm** [comment]
Open Liberty currently [uses](https://github.com/OpenLiberty/open-liberty/blob/368348c7bf88b3295f8629b15437b0515157479d/dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/OASFactoryResolverImpl.java#L117) that method.

If you see multi-thread bugs with it, can you please open a separate issue?

**Comment by rmannibucau** [comment]
@arthurdm I know but OpenLiberty can drop it without any issue too technically. On a user side it just open ways to break the app and on a framework side it enables a framework to not be compatible with another one so can only see the "quickfix" usage of that method. Since MP-openapi is not yet really used I'd rather break the API now with a versioning upgrade rather than keeping it and breaking apps when it will be used.

Just my 2cts

**Comment by Emily-Jiang** [comment]
Without the setter, OSGi enviroment has to use spi fly, which is a big ask.
The setter is a much simpler approach.

Romain Manni-Bucau <notifications@github.com> 于 2018年5月28日 周一 17:32写道：

**Comment by rmannibucau** [comment]
@Emily-Jiang spifly or the ProviderLocator pattern of Geronimo (this one is not a big ask ;)). The issue with that setter is you ensure you break users and prevent libs to use a clean API (= promise of issues). This is my concern.

**Comment by arthurdm** [comment]
@rmannibucau - it's still not clear to me what issues you're seeing with the current design.  Can you share some code that would help illustrate its problems?

**Comment by rmannibucau** [comment]
@arthurdm take a lib using this setter cause it wants to decorate the resolver and nested components, take another lib finding this idea very neat and doing the same, take a user doing the same for its app or company, take the container and finally take a user doing it to switch between provider at runtime during any request. All these use cases are broken. Putting an API must be with the guarantee it is secure and usable, if it is a container API then it is NOT an API but an internal of the vendor and there is no issue with it, IBM does it since 20 years without any issue in OSGi so I have a hard time to see why this API is needed.

Also note the loadSpi fails if there are 2 providers - instead of making it configurable  as in EE specs - so the setter is the only way to handle multiple providers at once and therefore it is the encouraged way to use the API and a runtime API but not implemented as such.

On an API and technical side the whole OASFactoryResolver is useless and can be dropped since the API can rely on CDI directly so I'd be in favor of dropping the implementation leakages from the API while we can still.

Hope it is clearer

**Comment by kenfinnigan** [comment]
It does appear that `setInstance` should at least check whether it's already been set before blindly replacing what's there.

This may very well be an issue in other specs as well, as I believe the same pattern has been applied to them all for OSGI

**Comment by rmannibucau** [comment]
I didn't see any singleton like this one is jwt-auth, config and opentracing so don't think it is a mainstream pattern.

**Comment by kenfinnigan** [comment]
The two below are other instances I've found:

https://github.com/eclipse/microprofile-config/blob/master/api/src/main/java/org/eclipse/microprofile/config/spi/ConfigProviderResolver.java#L173
https://github.com/eclipse/microprofile-rest-client/blob/master/api/src/main/java/org/eclipse/microprofile/rest/client/spi/RestClientBuilderResolver.java#L129

**Comment by rmannibucau** [comment]
Ok, config one should be dropped as well (i will open a ticket), it is not used by most vendors anyway and has the same pitfall
Rest client one is in the same case

Technically no real way to defend it so +1 to drop it

**Comment by Emily-Jiang** [comment]
How many OSGi runtimes have you searched? This is designed for OSGi runtime
without the need of dragging along spifly ir other service loadder support.
This is SPI class though.

Romain Manni-Bucau <notifications@github.com> 于 2018年5月29日 周二 15:08写道：

**Comment by rmannibucau** [comment]
@Emily-Jiang some dozens (geronimo spec jars). I understand why it was introduced but you explain it yourself: it is an internal of OSGi so why does it surface in a user API? this was likely an error and quick workaround so time to clean it (this is what this issue is about).

**Comment by arthurdm** [comment]
this is an **SPI**, not an **API**.   SPIs are for internal bundles from the vendor, not for user applications.

So this is meant to be for vendors to set their one and only OpenAPI-factory.

**Comment by rmannibucau** [comment]
Not really, a lot of SPI are user facing (check out deltapsike for instance) so SPI are API at the end, just with a more precise meaning.

**Comment by arthurdm** [comment]
ok - so that's the source of confusion - you and I, and perhaps a lot others, have a different view on what SPIs are.   In Open Liberty SPIs are not exposed to user applications.

**Comment by kenfinnigan** [comment]
I think the issue boils down to an `spi` package being in the `api` artifact.

So there's nothing preventing a user from utilizing classes from within the `spi` package.

Maybe there needs to be an `spi` artifact for these types of classes that aren't then present in the `api` artifact but can be used by implementations?

**Comment by rmannibucau** [comment]
@arthurdm does it mean the MP-api "spi" package is not usable? Since it is in the api jar it should but if so it is why there is this confusion, agree.

**Comment by rmannibucau** [comment]
@kenfinnigan think we need to align on EE so a loader (impl vendor dependent) and nothing more to load the impl. bean validation does it quite cleanly IMHO.

**Comment by arthurdm** [comment]
I agree that separating this into a different artifact would make it much more clear.  Perhaps that should be the outcome of this issue.

We tried to outline the usage in the [javadoc](https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/spi/OASFactoryResolver.java#L26-L27) of the class: 

```
This class is not intended to be used by end-users. It should be used by vendors to set their implementation of OASFactoryResolver.
```

As well as the [javadoc](https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/spi/package-info.java#L15-L16) of the package:

```
Service provider interface which allows vendors to set their implementations of OASFactoryResolver.
```

**Comment by rmannibucau** [comment]
I saw it but frameworks are still in the scope of this method and not a single container strictly need it as proven by last 20 years of EE ;)

**Comment by arthurdm** [comment]
the consensus today is that this package should be part of an `SPI` maven artifact, to make it clear that it's not for application developer consumption, as per https://github.com/eclipse/microprofile-open-api/issues/224#issuecomment-392878701

**Comment by rmannibucau** [comment]
This is fine while not part of the microprofile package since it is only for a single vendor.

**Comment by wojtczat** [comment]
I'll work on this issue

**Comment by arthurdm** [comment]
Completed via PR #260
