### ISSUE TITLE
Yaml should be optional

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile-open-api#228]
MP base is CDI+JAXRS+JSON, therefore yaml support should be optional and not enforced in the spec and tck.

**Comment by arthurdm** [comment]
I can appreciate your position, but given the history of Swagger and OpenAPI heavily favour YAML, we would be going against the API industry if we didn't make YAML the default.

**Comment by rmannibucau** [comment]
@arthurdm having an "OPTIONAL" in the spec is fine, pushing a standard for YAML in JakartaEE/Microprofile is fine (Yaml-P and Yaml-B), having to depends hardly on something which is not in the platform and out of scope for the spec is very bad.

See it this way: who does handle the serialization in the platform? JAX-RS right? What does Microprofile provides for JAX-RS? JSON and that's it. So best you can do is to make it optional for vendors.

Also swagger is mainly about design but every other usages are JSON based (communication between apps, persistence, ui, ...) so recentering the spec on the mainstream format is good. Making Yaml an extension is very valuable but too intrusive in implementations today to makes sense, in particular when you take into consideration that the designers will user yaml and serve it outside this spec (servlet or so). So no real gain but real drawbacks to enforce its support.

**Comment by arthurdm** [comment]
Closing this based on the fact that OAS3 spec defines both YAML and JSON as formats: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#format

**Comment by rmannibucau** [comment]
Where is the designer in MP? Nowhere so yaml is not yet needed. Also check the proposal: mention it as encouraged but optional as most spec do.

**Comment by rmannibucau** [comment]
up? this issue is not solved. Keep in mind this is NOT cause OAS3 defines YAML and JSON that MP *MUST* support it. If OAS3 defines that XML is support you don't have to add it. Specifications generally say "X MUST be supported and Y/Z are optional". Since MP is only about JSON and has no link *at all* with Yaml then this is what should be done here.

**Comment by arthurdm** [comment]
thanks for the feedback @rmannibucau - I will re-open this issue, to be discussed in the next hangout (Monday, Oct 22 is the next one).

**Comment by msavy** [comment]
Just giving my thoughts/analysis of this:

One of the key purposes of this specification is to provide easy integration with the upstream OpenAPI specification, and to (relatively) seamlessly facilitate common usage patterns and formats. A very large proportion of live OpenAPI specifications are written in YAML -- by making this optional, we won't be able guarantee OAI MP implementations will work with a vast number of the OpenAPI specifications out in real-world usage. 

For example, a key part of the MP OAI spec allows the user to "bring their own spec" and serve this up (with various combinations of functionality, including merging it with scanned content, or just serving it up unmodified). These specs are likely to be in YAML if they were written by humans (or many of the editing tools).

Ultimately, if we want to make the spec successful, it needs to serve the users' needs by supporting _what they use, and their real-world workflows_. We can't possibly change another community (whom we are trying to attract) to fit our desire to homogenise MP.

On that basis I opine that mandatory YAML support is essential. The desire to settle on common data exchange formats within MP is an orthogonal issue.

Interested to hear other perspectives!

**Comment by rmannibucau** [comment]
@msavy the proposal is compatible with your description. If the spec is human written it is in yaml, I agree, but you can also export it in all tools in JSON or if not you trivially find a tool doing it so you can always deploy it as a JSON so this is not a real feature to deploy a static file as JSON for MP (you will also likely just use a static server to do that and not a MP server in practise). So this spec is at the end only about code first approach where JSON is more than enough.

**Comment by EricWittmann** [comment]
My $0.02 on this is that the MP+OAI spec should continue to require YAML as a format for the following reasons:

1) YAML is required by the OpenAPI specification
2) YAML is the most common format when creating API designs from e.g. editors and other tooling
3) Supporting YAML in the MP server does not introduce an unreasonable implementation burden

I would also add that the MP+OAI spec is not exclusively solving the code-first approach - in fact the specification goes out of its way to call out use cases that are either design-first, or else MP-bootstrapped and then imported into a design tool.  In both cases YAML format is highly convenient for users (although as you say it's certainly not required).  Obviously anyone can take a YAML file and convert it to JSON using existing tools.  Of course, the same is true of the MP server itself - it can trivially convert.

Ultimately, limiting this spec to JSON only might make sense from a MP-specific perspective, but IMO not from an OpenAPI perspective.

**Comment by msavy** [comment]
Requiring the user to convert or re-export their specification into JSON is not a good user experience, in my view.

In our experience, it's not hard to support YAML; I'm not convinced the burden on the implementor is sufficient to outweigh the burden and inconvenience inflicted upon the user (again, I'm very much interested to hear whether that's untrue for your situation?).

I think it's also not a good look, frankly. It says that we don't mandatorily support a commonplace format standard for OAI.

> so you can always deploy it as a JSON so this is not a real feature to deploy a static file as JSON for MP (you will also likely just use a static server to do that and not a MP server in practise)

Can you expand on this a touch? Not sure I understand. Are you claiming that the merging functionality is not useful?

**Comment by rmannibucau** [comment]
The burden is actually quite real cause yaml requires dead deps in most apps - all others are part of mp core in v2.

And yes, the merging is maybe 5% of use case and is bothering in the 95 others cause it leads to unexpected payloads without ignore configs. Once again if you are design driven you dont care of the impl and if you are code first you dont care of the representation. There are a tons of editors to ease the writing and exports of the spec and some dont even need raw yml or json writing so it is even better for the end users. If the user writes directly in yml, he can likely convert a file IMHO. So at the end yml support OOTB is really an excess of enthusiasm IMHO.

**Comment by rmannibucau** [comment]
Yaml deps I checked are either heavy compared to MP, or conflict for some or are a 1 man lib so not sure any of these is a good choice for prod. The point being it is not really used by *end users* anyway.

**Comment by rmannibucau** [comment]
> We cannot expect users to keep that in JSON just because MP OpenAPI can't handle YAML.

Keep in mind human driven API writing is done through forms today (Apigee, Restlet etc) so JSON is valid. Yaml user are "light dev" so can export as json easily. Also keep in mind I'm all for a "support" but not an "out of the box delivery". See it as a spec extension/appendix. So it is not goind "against" but going with the spec and users.

About the lib:

1. jackson (very fat for nothing, easily conflict - in particular if you have some scala somewhere, but maintained - even if the dev community is not diversed the user one is)
2. Yamlbeans: needed some hack to handle MP-OpenAPI model - or use another model which is not really an option since user should be able to handle it as well at the end.
3. SnakeYAML: "1 guy" project

@geronimo I used jackson for the yaml only in an optional mode (not forced OOTB) and none of the user I'm aware of is using it.

**Comment by msavy** [comment]
> The point being it is not really used by _end users_ anyway.

@rmannibucau That's just not our experience (of course, something else may be true for your product).

Do you have some kind of strict size limitations for your implementation? For example, embedded systems?

**Comment by msavy** [comment]
@ivanjunckes which library are you guys using for your YAML support, currently?

@kenfinnigan Do you guys have a preferred/recommended YAML library in Thorntail? I see both snakeyaml and jackson's jackson-dataformat-yaml used in a fair number of places.

**Comment by rmannibucau** [comment]
@msavy just the general rule to not require more than the user expect to keep control of the stack, limit the vulnerability and keep fast uploads, builds and runs. Today the mp distro is < 14M so yaml is significant. Fyi tomee uses jackson which breaks apps (understand users) and the server in several cases.

**Comment by msavy** [comment]
Okay, just going to close things out from my side:

My position is that making YAML optional would meaningfully damage the specification; I disagree with your assessment that it's an unimportant/marginal format for OAI MP. 

The technical aspects of YAML support are not problematic for us at all (i.e. Jackson was already available, we just added the YAML module). But, I think the technical issues are an orthogonal concern -- we should be ensuring the best possible experience and portability for our users.

Hopefully our view of things is clear; very interested to hear back from other vendors and hear their assessments and analyses.

**Comment by rmannibucau** [comment]
Done at https://github.com/eclipse/microprofile/issues

**Comment by kenfinnigan** [comment]
Thanks @rmannibucau

**Comment by ivanjunckes** [comment]
> which library are you guys using for your YAML support, currently?

We are using geronimo-open-api, which uses jackson like Romain said.

**Comment by kenfinnigan** [comment]
This was discussed at the MP Architecture call today.

There was agreement that all MP specs should output data in JSON format. However, the default format can be something other than JSON where an external specification or industry standard dictates something different. Examples of that being YAML with OpenAPI and Prometheus with Metrics

**Comment by msavy** [comment]
Thanks for the engagement, Ken. Much appreciated.
