### ISSUE TITLE
Missing addXXX methods

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile-open-api#229]
For consistency with other patterns:

- Encoding#addHeader is missing
- Operation#addCallback

also the addAPI is addApi, not sure it was intended

**Comment by arthurdm** [comment]
+1.  I agree with these additions.

**Comment by arthurdm** [comment]
Confirmed with the group in today's hangout.

**Comment by jmini** [comment]
I have opened https://github.com/eclipse/microprofile-open-api/pull/249 to add the 2 missing methods.

@rmannibucau, what do you mean with:

> also the addAPI is addApi, not sure it was intended

**Comment by rmannibucau** [comment]
@jmini https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/models/responses/APIResponses.java#L41 should be addAPIResponse (dont recall if there are others but this kind of naming).

**Comment by jmini** [comment]
After #255, we will keep `APIResponses` because it is extensible, so the name should be adjusted as described here => PR #258 for 1.1
