### ISSUE TITLE
models package is not (de)serializable OOTB easily

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile-open-api#231]
OpenAPI is by design serializable in yaml, json and sometimes in xml.

Since it is a mainstream exchange format the default binding should match mainstream serializer rules (pojo).

Current model doesnt at all and it makes it hard for users to switch of serializer or use the model for other needs than the default one (/openapi) which reduces a lot the portability and usability of that spec.

Can the model be reworked to ensure it stay simple or at least produce a POJO only model (toPojo() can work but a straight pojo model instead of interface based sounds better)

**Comment by arthurdm** [comment]
The serialization format is YAML or JSON - which can then be fed into a generator (https://github.com/OpenAPITools/openapi-generator) to produce clients or server impls.  That's the pattern we support.

What we would like to do is contribute to the OpenAPITools project so that we can go from OAS3 -> MP OpenAPI (server) and OAS3 -> MP Rest Client (client).

**Comment by rmannibucau** [comment]
well being said JSON is everywhere and will not be removed anytime soon, it is really ok to have yaml optional. Yaml is mainly an end user oriented format but not a runtime format. Microprofile being a runtime solution, it makes sense to enable Yaml if desired but not promote it more than needed. In particular cause most of users will want to use the openapi ui and only json is supported by most implementations so yaml is not as mainstream as the initiative would like today (which, once again, is aligned with the fact to make its support optional)

**Comment by struberg** [comment]
yaml is the new XML. It should really be optional. 
Also YAML is not EE native nor MP native. Whereas JSON-P is in MP-1.0 plus additionally JSON-B in MV-2.0.

**Comment by arthurdm** [comment]
Thanks for the feedback guys.

I still think we have taken the right approach in supporting both YAML and JSON.   While YAML is not officially defined in EE, it's defined by the official OpenAPI v3 spec: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#format.

**Comment by arthurdm** [comment]
Both concerns from this issues have been addressed:

1. The model serialization.  This is addressed by [this comment](https://github.com/eclipse/microprofile-open-api/issues/231#issuecomment-399766865), remembering that `/openapi` is the aggregation of all documentation mechanism (we can't just look at models separately), and it is the serialization / deserialization protocol.  

2. Format (YAML/JSON).  As referenced by [this comment](https://github.com/eclipse/microprofile-open-api/issues/231#issuecomment-400444846) we must support both formats.  Furthermore, YAML has become the `de facto` standard for representing API & microservices resources (e.g. kubernetes, docker compose, etc).

**Comment by rmannibucau** [comment]
1. is wrong -> this is one serialization so maybe 10% of user usages
2. this is inconsistent with the platform and not needed at all, we are not building a "de facto" standard but a standard
