### ISSUE TITLE
TCK use JAXB?

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile-open-api#233]
Hi guys,

org.eclipse.microprofile.openapi.apps.petstore.model.User uses jaxb as binding which is weird for any MP spec since only JSONP and very recently JSONB are supported so JAXB can be an optional extension but must not be part of the default TCK coverage.

Romain

**Comment by mrglavas** [comment]
The JAX-RS JSR specifies JAXB as a context provider for XML. I believe that implies that any MP spec supporting JAX-RS also has a dependency on JAXB and that this binding is the default for XML objects.

**Comment by rmannibucau** [comment]
Not really, it is a lazy coupling in all implementation and a concern now it gets dropped from the jvm and only json is the common format between mp specs.

Note that deopping these annotations still works for tcks and that mp2 requires rather jsonb than jaxb which is neither promoted nor provided by default mp stack.

Since @schema is here short term fix is to just remove jaxb bindings from tcks.

**Comment by arthurdm** [comment]
@andymc12 - thoughts on this?     I think @mrglavas (and the TCK we have) is correct.

**Comment by andymc12** [comment]
@arthurdm - the TCK looks fine to me.  I can understand the argument that MP might not want to include JAXB (especially now that it is being removed from the JDK in Java 11...), but this text is in both the JAX-RS 2.0 (MP 1.X) and 2.1 (MP 2.X) specs:
```
An implementation MUST include pre-packaged MessageBodyReader and MessageBodyWriter im- plementations for the following Java and media type combinations:
...
javax.xml.bind.JAXBElement and application-supplied JAXB classes XML types (text/xml and application/xml and media types of the form application/*+xml).
```

This means that a JAX-RS application should be able to depend on JAXB (provided by the runtime) to serialize/deserialize objects to/from XML.  

Hope this helps, Andy

**Comment by arthurdm** [comment]
Thanks for the feedback @mrglavas and @andymc12!

@rmannibucau - I think it's hard to argue with the EE spec when it states that it `MUST` be this way. =)

**Comment by rmannibucau** [comment]
@arthurdm it is actually trivial to argue it: mp platform can relax any EE requirement. This requirement is there cause jaxb is one of the core spec of ee, it is nowhere in mp core required so kot needed at all.

Also note than dropping jaxb model keeps the tck the same and solves that issue so pby no need to discuss it much and just embrace java9 and later.

**Comment by OndrejM** [comment]
You are right, @rmannibucau - whether MP also includes EE spec dependencies isn't clarified at all anywhere in MP. But we took the JAX-RS into MP as a whole so that also implies that JAXB is included in MP. I think we should clarify this at the arch. board level how to address EE spec dependencies.
