### ISSUE TITLE
Questions about org.eclipse.microprofile.openapi.models.PathItem

### ISSUE THREAD

**Issue by jmini** [eclipse/microprofile-open-api#234]
I am new to the Microprofile project, I hope this is the appropriate channel to start a discussion.

How definitive are the model interfaces introduced with version MicroProfile release 3.1?
I understand that Swagger Core was used as reference, but maybe some stuff can be improved when establishing a standard.

Today I have worked a lot with `PathItem` and `Operation` (I work with swagger-core) and I was curious to see how you guys did solve this.

Here 2 questions about `org.eclipse.microprofile.openapi.models.PathItem`.

Thank you in advance for the discussion.

---

**Question 1:** why are the convenience methods that provides all operations as list or as map called `readOperations()` and `readOperationsMap()`:

https://github.com/eclipse/microprofile-open-api/blob/bffd7ace546bd964cb46d29dcf2114c8ac28fe80/api/src/main/java/org/eclipse/microprofile/openapi/models/PathItem.java#L266-L278

I like the way the Kaizen-Parser solves this by providing a map (they do not have the enum for HTTP operation type):

```java
	Map<String, Operation> getOperations();
```
([source](https://github.com/RepreZen/KaiZen-OpenApi-Parser/blob/ad8fa48166e0540ba09ed028292a3a06aa512516/kaizen-openapi-parser/src/main/java/com/reprezen/kaizen/oasparser/model3/Path.java#L31))

If we take the best of both words:

```java
Map<PathItem.HttpMethod, Operation> getOperations();
```

With the constraint that the returned `Map` should never be `null` and that the map is a read-only access to the operations. (could be indicated in the Javadoc)

If you just want the collection of operations `getOperations().values()` can be called. I do not think that a method returning `List<Operation>` is requested.

---

**Question 2:** In Swagger-Core the `String` path of an `PathItem` is an important information that belongs in my opinion to the `PathItem` object, but that is missing the `Operation` object.
 
To access to this information you need the corresponding `Entry<String, PathItem>` of the `Paths` map holding the `PathItem`.

Because this information is not present, you need always to pass it with in each `PathItem` instance in of your methods:

```java
void printOperationsInfo(String path, PathItem path);
```

Or to have your own holder class: 

```java
static class PathItemWithPath {
    final String pathString;
    final PathItem path;

    public PathItemWithPath(final String pathString, final PathItem path) {
        super();
        this.pathString = pathString;
        this.path = path;
    }
```

The Kaizen-Parser Model did solve this with:

```java
	String getPathString();
```
([source](https://github.com/RepreZen/KaiZen-OpenApi-Parser/blob/ad8fa48166e0540ba09ed028292a3a06aa512516/kaizen-openapi-parser/src/main/java/com/reprezen/kaizen/oasparser/model3/Path.java#L13))

Maybe the wording is not ideal, but the information is really important when you manipulate `PathItem` instances.

**Comment by arthurdm** [comment]
hey @jmini - welcome to MicroProfile and thanks a lot for your feedback!   It's really cool to merge best practices from industry leaders like Kaizen and Swagger, so definitely a good direction.  

I agree with both your suggestions.  For #1 I suspect that's a history serialization/deserialization issue where there wasn't a field called `operations` so `getOperations` was ruled out - but whatever historic reasoning was used, I don't see any issues with the proposal.  

For #2, we have [Paths](https://github.com/eclipse/microprofile-open-api/blob/bffd7ace546bd964cb46d29dcf2114c8ac28fe80/api/src/main/java/org/eclipse/microprofile/openapi/models/Paths.java#L41) which uses `name` as the path string, so I would suggest we add `String getName();` just for consistency with its parent model.  

If you would like to submit a PR for this, I will gladly review.

Thanks.

**Comment by jmini** [comment]
For `#1`: what are the guidelines? It is allowed to just remove:

```
 List<Operation> readOperations(); 
 Map<PathItem.HttpMethod, Operation> readOperationsMap(); 
```

And to add:

```
Map<PathItem.HttpMethod, Operation> getOperations();
```

Or should I work with the `@Deprecated` annotation?

---

For `#2`: I think it will file an other Issue to track it, because this is a pattern you see everywhere where you have a map?

**Comment by arthurdm** [comment]
For `#1` you can deprecate those methods (pointing to the new ones).  Our next release is just a point release (1.1) so we need to keep backwards compatibility.

Sounds good, let's deal with `#2` in  a separate issue.   Thanks!

**Comment by arthurdm** [comment]
I think all the changes here were completed in PR #243 - closing.

**Comment by jmini** [comment]
The issue described as `#2` (being able to have the key of an entity as part of this entity) was not opened yet.

**Comment by arthurdm** [comment]
cool, good catch.     do you want to open that one @jmini?

**Comment by jmini** [comment]
New issue: https://github.com/eclipse/microprofile-open-api/issues/264

the issue is only a draft, I never took the time to investigate the proposed concept completely. But I am sure that the concept is necessary. It simplifies the manipulation code a lot.
