### ISSUE TITLE
Models: using default methods for builder methods?

### ISSUE THREAD

**Issue by jmini** [eclipse/microprofile-open-api#236]
In the `org.eclipse.microprofile.openapi.models` package and sub-packages, the builder-pattern is used:

```java
    T getXyzAbcd();

    void setXyzAbcd(T xyzAbcd);

    U ayzAbcd(T xyzAbcd);
```

The `ayzAbcd(T)` method is just a builder method.

Could this method be a default method?

```java
    default U XyzAbcd(T xyzAbcd) {
        setXyzAbcd(xyzAbcd);
        return this;
    }
```

In my opinion it would ease the work of people who wants to create an implementation of the model interfaces.

Or is there a reason to not do this?

**Comment by arthurdm** [comment]
We agreed with this in today's hangout.  This issue will be used to drive the proposed work of adding the default impls for these simple builder methods.

**Comment by jmini** [comment]
I have created an example in https://github.com/eclipse/microprofile-open-api/pull/242 for the `Operation` class. Before I extend this pattern to all builders methods, I want to be sure that this is the idea we have discussed here.

**Comment by jmini** [comment]
> This issue will be used to drive the proposed work of adding the default impls for these simple builder methods.

Have you other changes than the one in #242 in mind?

**Comment by arthurdm** [comment]
that was all.  thanks again @jmini!
