### ISSUE TITLE
Models: Are ServerVariables really Extensible?

### ISSUE THREAD

**Issue by jmini** [eclipse/microprofile-open-api#245]
`org.eclipse.microprofile.openapi.models.servers.ServerVariables` represents a map of `org.eclipse.microprofile.openapi.models.servers.ServerVariable` in `org.eclipse.microprofile.openapi.models.servers.Server`

See spec: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#server-variable-object

I do not think that the map <variable-name, instance> is extensible. I know Swagger-Core has implemented it, but Kaizen Model did not and I think this is correct.

* Swagger-Core: [ServerVariables.java L57-L78](https://github.com/swagger-api/swagger-core/blob/110ae2bae21b7f2e64aff3691953c11a533a14c9/modules/swagger-models/src/main/java/io/swagger/v3/oas/models/servers/ServerVariables.java#L57-L78) 
* KaiZen: [Server.java](https://github.com/RepreZen/KaiZen-OpenApi-Parser/blob/ad8fa48166e0540ba09ed028292a3a06aa512516/kaizen-openapi-parser/src/main/java/com/reprezen/kaizen/oasparser/model3/Server.java#L37) is using `Map<String, ServerVariable>`,  there is no `ServerVariables` interface.

Of course `ServerVariable` is extensible.

**Comment by jmini** [comment]
Thank you for the quick feedback!

Well I guess that removing `extends Extensible` from the `ServerVariables` interface declaration is not a problem:

https://github.com/eclipse/microprofile-open-api/blob/7a28b39dfba5d8546efe5d195f547419f6761ad2/api/src/main/java/org/eclipse/microprofile/openapi/models/servers/ServerVariables.java#L25-L30

I am wondering if this is possible for a `1.1` version (that should stay backward compatible). Maybe I did not get it.

**Comment by EricWittmann** [comment]
I think the `ServerVariables` model should be removed and the `variables` property of `Server` should instead just be a `Map`.  What do you think, @arthurdm ?

**Comment by jmini** [comment]
@EricWittmann : I totally agree, but this is not only a `ServerVariables` question => #248.

**Comment by arthurdm** [comment]
hey guys - I totally agree here.    Probably just legacy stuff we can improve upon.

How about we tackle this in #248, since that will probably eliminate `ServerVariables` along with other similar interfaces?

**Comment by jmini** [comment]
I am not sure anymore about this. Maybe `ServerVariables` is extensible after all.

I found the corresponding method in KaiZen-Parser:
https://github.com/RepreZen/KaiZen-OpenApi-Parser/blob/172ae39be53dc25187314e2a5f19ad9a709ef6cf/kaizen-openapi-parser/src/main/java/com/reprezen/kaizen/oasparser/model3/Server.java#L51-L74

Usage example:

```java
openApi3.getServers().get(0).setVariablesExtension("xxxx", "yyyy");
```

**Comment by jmini** [comment]
The more I look at it, the more confuse I get.

I found the issue discussing if the ServerVariables are extensible or not: https://github.com/OAI/OpenAPI-Specification/issues/975

=> My understanding from Issue and from associated PR is that it was decided to not have extensions for server-variables.

---
*Current support in the java implementation*

KaiZen-Parser supports it. https://github.com/eclipse/microprofile-open-api/issues/245#issuecomment-415654948

Swagger-Core has code to support it but with commit https://github.com/swagger-api/swagger-core/commit/5e61d6a1b3b0251869be71cf2913210dfa870276 they have mark it as deprecated and as far as I have tested it, Swagger-Parser do not parse server-variables extensions for the moment (could be an issue).

---

Test spec:

```yaml
openapi: 3.0.1
info:
  title: Test extensions
  description: API under test
  version: 1.0.7
servers:
- url: https://api.test.com:{port}/{username}
  variables:
    x-test1: extension test
    port:
      default: "9999"
    username:
      default: alice
      enum:
      - alice
      - bob
```


---

My proposition:

Let ServerVariables extensible for the moment as the 2 java libs supports it.

**Comment by arthurdm** [comment]
Thanks for digging the OAS history on this @jmini!   

I guess the summary is that `ServerVariables` is a legacy artifact that was removed from the OAS spec during the RC process, but some tools have adopted it during their early implementation.

Since it no longer exists in the spec, I think we should deprecate `ServerVariables` in `1.1` and remove it in `2.0`.   So then it becomes less important on whether it's extensible or not, if it goes away. =)    

Each individual `ServerVariable` is still extensible, as per the spec.

**Comment by arthurdm** [comment]
Agreed on Sept. 10 hangout with conclusion from https://github.com/eclipse/microprofile-open-api/issues/245#issuecomment-417057124

**Comment by jmini** [comment]
A Model Test for `Server#setVariables(Map<String, ServerVariable> variables);` should be added, because for the moment there are only tests for the method that is deprecated: (Server#setVariables(ServerVariables variables);)
