### ISSUE TITLE
Models: Extensible.addExtension(..) should be a builder method

### ISSUE THREAD

**Issue by jmini** [eclipse/microprofile-open-api#246]
For consistency with other patterns:

All methods that allow to add an item in a list or in a collection are builder methods.

It should be also the case for:
```
org.eclipse.microprofile.openapi.models.Extensible.addExtension(String, Object)
```

**Comment by arthurdm** [comment]
yup, +1

**Comment by jmini** [comment]
Isn't also the builder method missing? I think it should be:

```
org.eclipse.microprofile.openapi.models.Extensible.extensions(Map<String, Object>)
```
