### ISSUE TITLE
Models: OpenAPI.path(..) should be OpenAPI.addPath(…)

### ISSUE THREAD

**Issue by jmini** [eclipse/microprofile-open-api#247]
For consistency with other patterns:

The method:
```
org.eclipse.microprofile.openapi.models.OpenAPI.path(String, PathItem)
```

Is the builder method to add an item into the `OpenAPI.getPath()` map. It should be:
```
org.eclipse.microprofile.openapi.models.OpenAPI.addPath(String, PathItem)
```

**Comment by arthurdm** [comment]
agreed

**Comment by jmini** [comment]
Maybe it should be:
```
org.eclipse.microprofile.openapi.models.OpenAPI.addPathItem(String, PathItem)
```

But there is also already:
```
org.eclipse.microprofile.openapi.models.Paths.addPathItem(String, PathItem)
```

Which does the same?

Maybe `OpenAPI.path(String, PathItem)` is just wrong and should be removed (or marked as deprecated with `1.1` to indicate that `getPahts().addPathItem(String, PathItem)` should be used instead).

**Comment by EricWittmann** [comment]
+1 to removing the `OpenAPI.path(String, PathItem)` method.

**Comment by arthurdm** [comment]
Discussed in Sept 10 hangout.  +1 to deprecate  `org.eclipse.microprofile.openapi.models.OpenAPI.addPathItem(String, PathItem)`  in `1.1` and remove it in `2.0`, as that functionality is available from `Paths`.

**Comment by jmini** [comment]
Pull requests to fix this issue:

* For version 1.1: #267
* For version 2.0: #268

**Comment by jmini** [comment]
Both PR are merged, I am closing this issue.
