### ISSUE TITLE
APIResponses should be extensible.

### ISSUE THREAD

**Issue by jmini** [eclipse/microprofile-open-api#254]
While I was reviewing #248, I have noticed that `org.eclipse.microprofile.openapi.models.responses.APIResponses` should be `Extensible`.

It is indicated here:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#responses-object
> This object MAY be extended with Specification Extensions.

### Swagger-core:

`io.swagger.v3.oas.models.responses.ApiResponses` has the methods:

* `getExtensions()`
* `addExtension(String, value)`
* `setExtensions(Map<String, Object>)`
* `extensions(Map<String, Object>)`

### KaiZen:

There is no `APIResponses` concept, but the `com.reprezen.kaizen.oasparser.model3.Operation` object holds the `// ResponsesExtension` methods:

* `Map<String, Object> getResponsesExtensions();`
* `boolean hasResponsesExtension(String name);`
* `Object getResponsesExtension(String name);`
* `void setResponsesExtensions(Map<String, Object> responsesExtensions);`
* `void setResponsesExtension(String name, Object responsesExtension);`
* `void removeResponsesExtension(String name);`

**Comment by arthurdm** [comment]
good find @jmini!
