### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by evelinec** [eclipse/microprofile-open-api#263]
While trying out this Open Liberty guide, https://openliberty.io/guides/bean-validation.html, which uses OpenAPI for user input and application execution. There are couple UI issues that can be improved. 

- [ ] It would help to move the response body page further up so after you click `Execute` it's the first thing the user sees. Or make the response body more prominent because at the moment it seems as important as the curl line.

- [ ] It's difficult to find the `Execute` button because of how long the blue bar is.

**Comment by kenfinnigan** [comment]
I believe these issues need to be opened against the OpenLiberty guide you're referring to and not the MP Open API specification

**Comment by arthurdm** [comment]
Thanks for the feedback @evelinec 

The UI is a value-add that Open Liberty adds on top of the MicroProfile OpenAPI spec, but it actually comes from a collaborative OSS work with the Swagger community, so the best place for an issue is: https://github.com/swagger-api/swagger-ui/issues  (although you would have to abstract it from `Open Liberty`).
