### ISSUE TITLE
Key of an element should be exposed in the element

### ISSUE THREAD

**Issue by jmini** [eclipse/microprofile-open-api#264]
Originally posted as `Question 2` in https://github.com/eclipse/microprofile-open-api/issues/234

---

When you work a lot with the model classes, for each member of a map (like `PathItem` element in the `Paths` object), you need to transport the key and the value everywhere because the information you need in contained in `Entry<String, PathItem>`.

Example:

```java
void printOperationsInfo(String path, PathItem path);
```

Or to have your own holder class: 

```java
static class PathItemWithPath {
    final String pathString;
    final PathItem path;

    public PathItemWithPath(final String pathString, final PathItem path) {
        super();
        this.pathString = pathString;
        this.path = path;
    }
```

---
The Kaizen-Parser Model did solve this with:

```java
	String getPathString();
```
([source](https://github.com/RepreZen/KaiZen-OpenApi-Parser/blob/ad8fa48166e0540ba09ed028292a3a06aa512516/kaizen-openapi-parser/src/main/java/com/reprezen/kaizen/oasparser/model3/Path.java#L13))

Maybe the wording is not ideal, @arthurdm pointed that the API needs to be consistent. PathItems are added with `addPathItem(String, PathItem)`:

https://github.com/eclipse/microprofile-open-api/blob/8e0f2479a00470911d64ae13a59c5cd78f4240c9/api/src/main/java/org/eclipse/microprofile/openapi/models/Paths.java#L34-L41

So the getter for the key in the owner map in `PathItem` should be called `getName()`.

---

This issue needs further discussion and checks.
Other requirement having switched to immutable maps (see #240).

Then we can add also TCK tests that ensure that when you mutate a map the exposed key is also updated.

**Comment by arthurdm** [comment]
+1.  I think this is an important improvement to the usability of these models.   

I like Kaizen's approach of calling this a "PathString", which ore accurately describes what it is.  What if we used `getPathString`, and then for consistency we just rename the input field of the related methods from `name` to `pathString`, such as `Paths addPathItem(String pathString, PathItem item);`?

**Comment by arthurdm** [comment]
Discussed in Sept 10 hangout.   +1 to this proposal.   Most places will still use `name`, but in cases where it makes sense to have another name we should change it (i.e. `pathString`)

**Comment by jmini** [comment]
Thank you for the transcript of the hangout.

For me the feature only makes sense when we have immutable maps (#240), otherwise the map content can be manipulated, without updating the name inside the value.

Example on `Paths` (assuming that the key is changed to `pathString`):
when `Paths addPathItem(String pathString, PathItem item);` is called if you later get the `PathItem` instance with the method `PathItem getPathItem(String pathString);` then `item.getPathString()` should return the same key.

With version `1.1` I do not see how this can be implemented. We need #248 to be solved completely. Meaning we need version `2.0`

**Comment by arthurdm** [comment]
Discussed in the hangout today.   One approach is to override the methods that `add` a single item to the map (in `1.1`) so that we can keep the key at the map level consistent with the key at the child object level.

**Comment by wojtczat** [comment]
@arthurdm I'll work on this issue

**Comment by jmini** [comment]
> One approach is to override the methods that add a single item to the map (in `1.1`) so that we can keep the key at the map level consistent with the key at the child object level.

The problem is that in `1.1` this is not the single way of mutating maps. Even the TCK also checks that adding an element with the `put(K,V)` method is possible:

https://github.com/eclipse/microprofile-open-api/blob/14590bc49671c3f8eeb416298fa17fdd2567551b/tck/src/main/java/org/eclipse/microprofile/openapi/tck/ModelConstructionTest.java#L378-L379

With `2.0` this approach is definitively possible.

---

An other aspect that should be considered / ensured: if a `PathItem` was already added somewhere (as value for specific key in the `Paths` map or as value for a specific key in the `Callback` element), it should not be possible to add it to an other map.

**Comment by jmini** [comment]
@wojtczat: Nice to see your PR #290 merged. 

For consistency reason, as @arthurdm suggested the parameter `name` in the `addPathItem(String, PathItem)` methods should be also renamed to `pathString`.

In `Paths`:

https://github.com/eclipse/microprofile-open-api/blob/8c8c6492afeeb3ffcd8e4456d69e6f6c6f2ed60e/api/src/main/java/org/eclipse/microprofile/openapi/models/Paths.java#L34-L41

In `Callback`:

https://github.com/eclipse/microprofile-open-api/blob/8c8c6492afeeb3ffcd8e4456d69e6f6c6f2ed60e/api/src/main/java/org/eclipse/microprofile/openapi/models/callbacks/Callback.java#L38-L49

@wojtczat: Do you want to work on this?

---

More generally, I still think that this change belongs to `2.0` and not `1.1`. I think the change should be cherry-picked on the `2.0` branch and reverted from `master`.

But I am not really impacted by what happen for the `1.1` version.

**Comment by arthurdm** [comment]
funny, I was thinking about this the other day. =)    In theory I guess it is a breaking change since someone's model implementation would not compile.  Unless we put a default impl returning `""`, but that's strange.

**Comment by arthurdm** [comment]
I think one of the things we missed is a `setPathString` method in `PathItem`.   For `1.1` we can then add a Javadoc to that method saying that its value is meant to always match the `key` used when inserting this `PathItem` into a Map.  Setting it to anything else, or not setting it, is a user error.

So for now, make the user of the model responsible for setting that, since we cannot control what they can do with the inherited `Map` mutations.  

Thoughts?

**Comment by jmini** [comment]
> I think one of the things we missed is a `setPathString(String)` method in `PathItem`.

I do not think that this method necessary at API level.

1) The KaiZen model is not providing a setter in their [`Path` interface](https://github.com/RepreZen/KaiZen-OpenApi-Parser/blob/2e0eb80eedc32186494cea3508ccee72bd6b421f/kaizen-openapi-parser/src/main/java/com/reprezen/kaizen/oasparser/model3/Path.java#L13)

2) In my opinion this will make the model more complex than necessary. For the moment we have more or less POJO. If we provide a setter for that is modifying the key of the element in the corresponding map, this means that the Object needs to keep track of the map it is included in. Then when a value is provided, it needs to check if the key exist in the map or not, and if not it needs to remove itself from the map and add itself as value for the provided key in the setter.

What is the use-case for this setter?

I think we should start by adding the getter as described in this issue. If there is a need for a getter we might add it as well, but right now I do not see the value compared to the complexity of implementation.

There is still work to do to finish it:

* Renaming of the keys
* TCK tests (the most important part in my opinion)

And then extend the pattern we are discussing to other elements in other maps.


> For `1.1` we can then add a Javadoc to that method saying that its value is meant to always match the `key` used when inserting this PathItem into a Map. Setting it to anything else, or not setting it, is a user error.

When I wrote this issue, I was more thinking that the user has nothing to set. He can access the value in order to not have to work with `Map.Entry<String, PathItem>` when he is iterating over the `paths` map.
This is the main use-case. From my work in OpenAPI generator, I know it is useful (because this is a pattern you see again and again).

**Comment by arthurdm** [comment]
I was thinking from a vendor's implementation side:  once a new PathItem is inserted into the Map I would like to set its path string field to match the `key` used - but if I am only working with the interface (https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/models/PathItem.java) then I don't currently have a way to `set` that field.

**Comment by jmini** [comment]
> I was thinking from a vendor's implementation side

I am pretty new to this API / vendor stuff, but isn't the API intended to be used by users of the lib? If some vendors need a setter they can add it, but it should not be exposed at API level to the user.

**Comment by arthurdm** [comment]
yup, it is indeed user-centric.   But, if there are things we can do to make it easier to implement the spec (for a vendor), so that they don't have to cast into impls, then that would be good too.   

I am ok either way with this - just wanted to bring up that vendors will have to cast (i.e. `((PathItemImpl)pathItem).setPathString(myString)`).

**Comment by jmini** [comment]
In consideration of the upcoming MicroProfile OpenAPI 1.1 release  scheduled for mid Dec (see #296), I think that the feature is not yet ready to be included in `1.1`.
This is one other reason why we should target this feature for `2.0`.

Action:
Revert the commit introduced by #290 on our `master` branch and continue to work on this on the `2.0` branch.

**Comment by arthurdm** [comment]
that sounds ok with me.  @jmini - if you wanted to do the revert, I am fine with this only going into 2.0.

**Comment by MikeEdgar** [comment]
We discussed this issue in today's meeting and the current thinking is that having adding this functionality may limit the re-usability of the value models and also introduce some challenges with keeping the things in sync. @jmini, is this something you still have an interest in pursuing/discussing further?
