### ISSUE TITLE
@Extension and list of strings value

### ISSUE THREAD

**Issue by jmini** [eclipse/microprofile-open-api#269]
Version 3.0.1 specify the type of vendor extensions that can be used ([Specification Extensions](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#specificationExtensions)):

> The value can be `null`, a primitive, an array or an object. Can have any valid JSON format value.

For the moment, the java annotation `@org.eclipse.microprofile.openapi.annotations.extensions.Extension` supports only `String` type as value.

Usage example in the TCK, lines 330 and 331:

https://github.com/eclipse/microprofile-open-api/blob/8e0f2479a00470911d64ae13a59c5cd78f4240c9/tck/src/main/java/org/eclipse/microprofile/openapi/apps/petstore/resource/PetResource.java#L313-L332

---

My use case is to store an array of string as value:

Yaml input example:
```yaml
paths:
  /sample/pet:
    get:
      operationId: updatePet
      responses:
        default:
          description: default response
      x-custom: 
         - xxx
         - yyy
```

Preview (Swagger-UI):

<img width="419" alt="Extensions preview in Swagger Editor" src="https://user-images.githubusercontent.com/1222165/37815384-dff33138-2e6e-11e8-95ba-b00477b597a0.png">

I have the feeling that this is not possible at the moment with microprofile-open-api annotations.

**Comment by jmini** [comment]
As comparison, tested with:

```xml
    <dependency>
      <groupId>io.swagger.core.v3</groupId>
      <artifactId>swagger-jaxrs2</artifactId>
      <scope>compile</scope>
      <version>2.0.4</version>
    </dependency>
    <dependency>
      <groupId>io.swagger.core.v3</groupId>
      <artifactId>swagger-jaxrs2-servlet-initializer</artifactId>
      <version>2.0.4</version>
    </dependency>
```

Java code:

```java
  @GET
  @Path("/{petId}")
  @Operation(
          summary = "Find pet by ID",
          description = "Some description ...",
          extensions = {
                  @Extension(properties = {
                          @ExtensionProperty(name = "x-custom", value = "[\"xxx\", \"yyy\"]", parseValue = true)
                  })
          },
          responses = {
                  @ApiResponse(description = "returns the corresponding Pet", content = @Content(schema = @Schema(implementation = Pet.class))),
                  @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
                  @ApiResponse(responseCode = "404", description = "Order not found")
          }
  )
```

`parseValue = true` in `@ExtensionProperty` does what I need.

Not sure what the solution in microprofile is.

**Comment by arthurdm** [comment]
Discussed in today's hangout.  We agree with the addition of a `parseValue` field in that annotation.  It can also be used to parse other types, like number (eg.  value="12", parseValue=true)
