### ISSUE TITLE
Link model requestBody field should be String or Object

### ISSUE THREAD

**Issue by arturdzm** [eclipse/microprofile-open-api#27]
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#linkObject

Right now its of type RequestBody but specification states a literal Any | {expression} type.

**Comment by arturdzm** [comment]
RequestBody can be any literal value such json number, array or string or boolean


```
openapi: '3.0.0'
info:
  title: API
  version: 1.0.0

paths:
  /path:
    get:
      tags: 
        - API
      description: 'Path with callback'
      responses:
        200:
          description: Ok
          links:
            link1:
              operationId: linkPath
              requestBody: 200.0
            link2:
              operationId: linkPath
              requestBody: "a string"
            link3:
              operationId: linkPath
              requestBody: ["val", "val2", "val3"]
              
  /link:
    get:
      tags: 
        - API
      description: 'Link path'
      operationId: linkPath
      responses:
        200:
          description: Ok
```

Example Object also has value of type Any and its defined as Object:
 https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#exampleObject

**Comment by arthurdm** [comment]
+1 

We should keep consistency with Example.value

**Comment by arthurdm** [comment]
@arturdzm - will you be working on this one?

**Comment by arthurdm** [comment]
Fixed by https://github.com/eclipse/microprofile-open-api/pull/28
