### ISSUE TITLE
create mvn snapshot artifacts

### ISSUE THREAD

**Issue by stbischof** [eclipse/microprofile-open-api#282]
I cant find snapshot artifacts of the current version in any public repository.

**Comment by stbischof** [comment]
i see, but there is no snapshot version

**Comment by arthurdm** [comment]
I am wondering if a lot of app developers would take advantage of the snapshot version, vs using the stable release?

**Comment by jmini** [comment]
I know one scenario where I like to use already built SNAPSHOT version:
When I would like to know if my implementation is still compliant with the next version of the project, then it makes sense to use the SNAPSHOT version (on a feature branch for example).

On main branches and for released version of my project I use only released version.

**Comment by stbischof** [comment]
that is the normal development life-cycle.. if you want that others are up-to date with your spec and wants to give (pre-release) feedback from the point of view of an implementing developer is absolutely helps to have snapshots.

**Comment by arthurdm** [comment]
cool, good points.

**Comment by jmini** [comment]
I have created a job:
https://ci.eclipse.org/microprofile/job/Open-API-maven-snapshots/

Based on the input of this wiki page:
https://wiki.eclipse.org/MicroProfile/Continuous_Integration

For the moment I am only doing a "maven verify" to ensure that Jenkins is working, but this should be changed to "maven deploy" when I am sure that the setup is done correctly in the POM (I will check this as next step).

**Comment by jmini** [comment]
I have noticed that the Microprofile-RestClient project is pushing SNAPSHOTS to:

```
https://oss.sonatype.org/content/repositories/snapshots/
```

I have copied the settings of their job [RestClient-maven-snapshots](https://ci.eclipse.org/microprofile/job/RestClient-maven-snapshots/) and I managed to do a first maven deployment of the SNAPSHOT version, see the [openapi](https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/microprofile/openapi/) folder.

Maven GAV:
```xml
<groupId>org.eclipse.microprofile.openapi</groupId>
<artifactId>microprofile-openapi-api</artifactId>
<version>1.1-SNAPSHOT</version>
```

@stbischof : can you check if this works for you?

**Comment by jmini** [comment]
The SNAPSHOT versions continue to be published.

With this config:

```xml
    <repositories>
        <repository>
            <id>snapshots-repo</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases><enabled>false</enabled></releases>
            <snapshots><enabled>true</enabled></snapshots>
        </repository>
    </repositories>
```

the SNAPSHOT Versions can be consumed in a maven build.

---

Closing this now.

@stbischof feel free to reopen/comment if you need anything.
