### ISSUE TITLE
Clarify behaviour of setter/builder methods with list / map parameter

### ISSUE THREAD

**Issue by jmini** [eclipse/microprofile-open-api#284]
When a list or a map instance is passed to as setter method (or a builder) the implementation should create a copy of the items.

Examples:

1) setting an immutable list map

```java
List<Parameter> parameters = Collections.singletonList(pathParam);
operation.setParameters(parameters);
operation.addParameter(queryParam); // should work.
```

In my opinion this should work.

2) putting an element after having passed the list map instance.
 

```java
Map<String, Callback> callbacks = new LinkedHashMap<>();
callbacks.put("myCallback", callback);
operation.setCallbacks(callbacks);

callbacks.put("myCallback2", callback2);

operation.getCallbacks(); // should only contains 'myCallback'
```

In my opinion the second addition in the map should not modify the map in the OpenAPI instance.

For both cases, this might be a decision that is taken at implementation level (I am open for discussion).

---

My propositions:

**For 1.1**: 

Relax the TCK in oder to allow implementation to do some copy of map/list internally. Right now some code position in `ModelConstructionTest` are assuming to get the same instance.
The check should check for equality instead, because the list/map content must be the same but the list/map instance can be an other one.

_NB: I have prepared the change, but I made it on top of #283, so lets go with this first._

**For 2.0**: 

Depending on the consensus, the TCK should enforce the implementation to do a copy of the map in the list/map setters.

I think it would be better so, but this is subject to debate.

I can accept this to be only a constraint that I add for my own implementations.

**Comment by arthurdm** [comment]
I agree @jmini.  Implementations should copy the contents of the list/map, not use the actual instance.

**Comment by jmini** [comment]
PR for `1.1`: https://github.com/eclipse/microprofile-open-api/pull/286

**Comment by jmini** [comment]
PR for `2.0`: #293

**Comment by jmini** [comment]
Both PRs are merged. Closing this.
