### ISSUE TITLE
Investigate new OAS 3.0.2 version

### ISSUE THREAD

**Issue by arthurdm** [eclipse/microprofile-open-api#285]
Investigate the `3.0.2` version of the OAS spec to see if there's anything we should react to.  

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md

**Comment by jmini** [comment]
Is there a diff or a blog post available somewhere, that describes the changes?

**Comment by arthurdm** [comment]
There's a change log here: https://github.com/OAI/OpenAPI-Specification/releases/tag/3.0.2

**Comment by EricWittmann** [comment]
Having a look at this now.  Apologies for the delay.

**Comment by EricWittmann** [comment]
OK after doing my own diff of the specification (yay for markdown!) between versions 3.0.2 and 3.0.1, I'm satisfied that there are no changes which impact the Microprofile OpenAPI specification.

I will not be offended if someone else wants to double-check, but I'm comfortable saying there's nothing to be done...and thus closing this issue.

**Comment by jmini** [comment]
I had a look from an other point of view (starting with our code).

---

I found that some TCK tests are checking for “Start with `3.0.`” so this is OK (vendors can switch to `3.0.2` and the tests will still be valid)

Example:
https://github.com/eclipse/microprofile-open-api/blob/8c8c6492afeeb3ffcd8e4456d69e6f6c6f2ed60e/tck/src/main/java/org/eclipse/microprofile/openapi/tck/AirlinesAppTest.java#L53-L58

---

Other places mention `openapi: 3.0.0`, we might want to update those places.
[microprofile-openapi-spec.adoc Line 412](https://github.com/eclipse/microprofile-open-api/blob/8c8c6492afeeb3ffcd8e4456d69e6f6c6f2ed60e/spec/src/main/asciidoc/microprofile-openapi-spec.adoc)

https://github.com/eclipse/microprofile-open-api/blob/8c8c6492afeeb3ffcd8e4456d69e6f6c6f2ed60e/tck/src/main/resources/openapi.yaml#L15-L18

https://github.com/eclipse/microprofile-open-api/blob/8c8c6492afeeb3ffcd8e4456d69e6f6c6f2ed60e/tck/src/main/resources/simpleapi.yaml#L1-L8

I have created https://github.com/eclipse/microprofile-open-api/pull/297 for this.

What do you think? (I am fine with not merging it).

**Comment by arthurdm** [comment]
Thanks for the work on this guys.  Closing this, as PR #297 has been merged.
