### ISSUE TITLE
Add support for Patch

### ISSUE THREAD

**Issue by arthurdm** [eclipse/microprofile-open-api#291]
In EE8 / JAX-RS 2.1 there's now a `Patch` http method: https://javaee.github.io/javaee-spec/javadocs/javax/ws/rs/PATCH.html

This issue will integrate that into the MP OpenAPI spec.

**Comment by jmini** [comment]
Beside setting the new version in the TCK pom to:

```xml
<jaxrs.version>2.1</jaxrs.version>
```

And adding a test, is there something else to do?

---

I am not really aware of the versioning policy at micro profile, but changing the required JAX-RS version (from JAX-RS 2.0 Java EE 7 to JAX-RS 2.1 Java EE 8) is something that can be done on a minor version of OpenAPI-Microprofile (`1.1`)?

**Comment by arthurdm** [comment]
I think that's probably it.  Although the TCK tests would have to cover both the annotation case (using `@Patch`) as well as the design-first case (via an OAS3 doc that has `patch`).   The PathItem model class already handles Patch so that should be good.

For the versioning, I believe the EE7 vs EE8 only applies to the umbrella MP release (like MicroProfile `1.x` vs `2.x`).   So we would release MicroProfile OpenAPI `1.1 `which would be only part of MicroProfile `2.x` since it will depend on EE8.

@kwsutter @kenfinnigan - did I get that right?

**Comment by EricWittmann** [comment]
I'll have a look at this.

**Comment by jmini** [comment]
PR: #308
