### ISSUE TITLE
Openapi 3.0 document generation at maven build time

### ISSUE THREAD

**Issue by 4040** [eclipse/microprofile-open-api#294]
Hi am trying to generate API documentation by scanning all openapi annotation which we used in java at maven build time as json or YAML rather than Runtime in liberty server.Its working fine with runtime.

maven
 ```
<dependency>
    <groupId>org.eclipse.microprofile.openapi</groupId>
    <artifactId>microprofile-openapi-api</artifactId>
    <version>1.0.1</version>
    <scope>provided</scope>
  </dependency>
```
Am looking for any maven plugin to generate Api document at Buildtime for openApi

**Comment by arthurdm** [comment]
Thanks @4040 

One path forward is to engage the OpenAPITools community (fyi @jmini), and perhaps propose an MP OpenAPI equivalent to https://github.com/openapi-tools/swagger-maven-plugin, something like `https://github.com/openapi-tools/mp-openapi-maven-plugin`?

As we spoke before, the limitation of that tool is that it would not support `runtime` aspects of the specification such as `OASReader` and `OASFilter`, but that may be ok for a lot of users.

**Comment by arthurdm** [comment]
I just realized there's https://github.com/openapi-tools and there's https://github.com/OpenAPITools.   @jmini  - do you know the difference?

**Comment by arthurdm** [comment]
@rmannibucau - I wonder how [Geromino](https://geronimo.apache.org/microprofile/openapi.html) has a plugin that provides `openapi.json`, in the sense that the MP application could have user-provided `OASReader` or `OASFilter` that could be relying on runtime / environment attributes?

**Comment by rmannibucau** [comment]
@arthurdm you mean the maven plugin? Current impl ignores OAS* extension points - but good suggestion ;). The point is that this plugin is to use the API as provided and serve it statically without MP at all (with httpd or ngnix typically). Users tend to either hardcode the values or have a postprocessing build step - it is json after all - to customize it. I have very good feedbacks of that without these API, this is why i opened an issue saying it can be dropped thanks to either java streams on the model or directly jsonobject.

**Comment by jmini** [comment]
This was discussed also on Gitter with @EricWittmann:

> There isn't a MicroProfile OpenAPI generator maven plugin, unfortunately. If you're interested, I don't think it would be too hard to write one. You could use the SmallRye library to do most of the work: https://github.com/smallrye/smallrye-open-api
> SmallRye generator can be used at build time (it just needs the deployment artifact i.e. the JAR/WAR), but @arthurdm makes a good point - the `Reader` and `Filter` features of MP+OpenAPI will likely not work at build time (depending on their respective implementation classes/dependencies)

I gave the SmallRye project a try:

Once you have the jandex (*) index of your code, the solution is ease:
```java
        OpenAPI openAPI = new OpenApiAnnotationScanner(null, index).scan();
        String yaml = OpenApiSerializer.serialize(openAPI, Format.YAML);
        System.out.println(yaml);
```

(*) jandex is a Java annotation indexer and offline reflection library:
https://github.com/wildfly/jandex

I have managed to compute the jandex-index for a single class with:

```java
        Path path = java.nio.file.Paths.get("<path>/todoapp/target/classes/com/example/todoapp/rest/TodoappEndpoint.class");
        InputStream stream = Files.newInputStream(path);

        Indexer indexer = new Indexer();
        indexer.index(stream);
        IndexView index = indexer.complete();
```
(first time I use jandex manually, do not take this code as perfect).

In order to work, I needed to have the dependencies of my project in the project running Jandex.

Probably you want to add the jandex-maven-plugin in your build to get the complete index of your project automatically and correctly. Then you should write a second plugin that take the jandex index and use the OpenApiSerializer to derive the OpenAPI Spec out of this.

**Comment by jmini** [comment]
@arthurdm : I am member of the "[OpenAPITools](https://github.com/OpenAPITools/)" organization on GitHub. I do not know "[openapi-tools](https://github.com/openapi-tools)", but I assume both follow the same kind of goal: providing tooling for OpenAPI/Swagger...

**Comment by MikeEdgar** [comment]
This issue was discussed in the Feb. 21, 2022 MP OpenAPI call and the group agreed there is no further action to take. It was noted that the SmallRye OpenAPI Maven plugin now exists that supports this functionality. 

https://github.com/smallrye/smallrye-open-api/tree/main/tools/maven-plugin
