### ISSUE TITLE
MicroProfile OpenAPI 1.1 release

### ISSUE THREAD

**Issue by arthurdm** [eclipse/microprofile-open-api#296]
This issue will act as an umbrella for our upcoming 1.1 release.  We're targeting mid December.

Main query: https://github.com/eclipse/microprofile-open-api/issues?q=is%3Aissue+is%3Aopen+label%3A%221.1+candidate%22

- [x] RC1
- [x] Final release

We need to also update this issue from the umbrella MP repo: https://github.com/eclipse/microprofile/issues/68

**Comment by jmini** [comment]
We have the [1.1+candidate](https://github.com/eclipse/microprofile-open-api/issues?q=is%3Aissue+is%3Aopen+label%3A%221.1+candidate%22) label to see the open issue.

I think one important point is #291: With MP-OpenAPI `1.1` we will request EE8 and integrate in Microprofile `2.x`, so having a solution for `@Patch` is important.

I will not reopen the debate here but for #264 I think we should target MP-OpenAPI `2.0` see https://github.com/eclipse/microprofile-open-api/issues/264#issuecomment-438949917

If the OAS 3.0.2 release requires some changes (see #285), integrating them in the `1.1` release is also important.

**Comment by EricWittmann** [comment]
@arthurdm you should drop a note to the MP group to let them know that we plan on doing a 1.1 release of OAI to be included in MP 2.2:  https://groups.google.com/forum/#!forum/microprofile

The next meeting is in a week and a half I think - someone from our spec should attend.

**Comment by arthurdm** [comment]
hey guys - good feedback.

Let's go through the list of 1.1 labelled items on Monday at the hangout to finalize what we want in vs defer.  Then we can work on how we get there =)     

Good point about the mailing list email - I will get on that.  I have been bad at attending at the overall meetings, I will try to attend - unless it's during my upcoming vacation Dec 1-8 =)

**Comment by arthurdm** [comment]
- [X] Email sent to the group.

**Comment by arthurdm** [comment]
RC1 MP OpenAPI 1.1 is out: https://search.maven.org/artifact/org.eclipse.microprofile.openapi/microprofile-openapi-parent/1.1-RC1/pom

**Comment by arthurdm** [comment]
Final release is out!  https://github.com/eclipse/microprofile-open-api/releases/tag/mp-openapi-1.1

**Comment by jmini** [comment]
Additional release to fix issues in the TCK: [`1.1.1`](https://github.com/eclipse/microprofile-open-api/releases/tag/mp-openapi-1.1.1)
