### ISSUE TITLE
ParameterIn is missing "Body"

### ISSUE THREAD

**Issue by bmhm** [eclipse/microprofile-open-api#299]
Dear all,

I am using `@FormParam` twice in a specific location which will be parsed from the POST body.

Problem is: `ParameterIn` does not have a body constant. It only has: 
`DEFAULT(""), HEADER("header"), QUERY("query"), PATH("path"), COOKIE("cookie");`

When adding a constant, please be so kind and also add a little bit of javadoc for each constant (especially default).

Thanks a lot!

**Comment by EricWittmann** [comment]
This specification requires/uses version 3.0.x of the OpenAPI specification, which no longer has a `body` parameter type.  Instead have a look at the `RequestBody` annotations.

**Comment by EricWittmann** [comment]
For reference, here is the annotation:

https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/annotations/parameters/RequestBody.java

And here is where you can learn more about request bodies in the OpenAPI specification:

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#requestBodyObject

And here is a specific example in the OpenAPI spec that describes how to express an operation with form data as input (in the body):

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#operation-object-example

**Comment by bmhm** [comment]
Thanks! That should be noted on
https://openliberty.io/guides/microprofile-openapi

**Comment by EricWittmann** [comment]
@arthurdm it sounds like that's something you'll need to handle. :)
