### ISSUE TITLE
TCK: create more realistic SecurityRequirement instances

### ISSUE THREAD

**Issue by jmini** [eclipse/microprofile-open-api#310]
Depending on how `SecurityRequirement` is implemented, the TCK `ModelConstructionTest` creates  `SecurityRequirement` instances that can be considered as equals and should not.

The TCK should contain values that are really different and more closer to the real values.

**Comment by jmini** [comment]
I have opened two PRs:

* 1.1: #311 
* 2.0: #312 

----

To reproduce the issue, you can add `hashCode()` and `equals(Object obj)` to the class implementing `SecurityRequirement`. In my opinion this implementation is acceptable.

The tck tests in `ModelConstructionTest` expect that if you call `createConstructibleInstance(SecurityRequirement.class)` twice in the same test, the 2 instances are different. Without any value and depending on the implementation this can be the case or not. The solution is to explicitly set different values (in order for the test to work with more implementation).

**Comment by arthurdm** [comment]
Both PRs merged.  Thanks @jmini!
