### ISSUE TITLE
TCK bugs in Release 1.1

### ISSUE THREAD

**Issue by EricWittmann** [eclipse/microprofile-open-api#327]
I found three problems with the TCK when updating smallrye:

1. The Airlines app test has an assertion using the wrong `operationId` value here:  https://github.com/eclipse/microprofile-open-api/blob/bd7706d3bacfc15e8253978b75348f54df1b232f/tck/src/main/java/org/eclipse/microprofile/openapi/tck/AirlinesAppTest.java#L264 The correct value is actually `getUserByName` as found here: https://github.com/eclipse/microprofile-open-api/blob/bd7706d3bacfc15e8253978b75348f54df1b232f/tck/src/main/java/org/eclipse/microprofile/openapi/apps/airlines/resources/UserResource.java#L454

2. The `ModelConstructionTest` checks that null scope descriptions (in the `Scopes` class) are disallowed here:  https://github.com/eclipse/microprofile-open-api/blob/bd7706d3bacfc15e8253978b75348f54df1b232f/tck/src/main/java/org/eclipse/microprofile/openapi/tck/ModelConstructionTest.java#L823  However I think null descriptions for scopes are OK and should be allowed.

3. The `ModelConstructionTest` checks that null scopes cannot be added in `SecurityRequirement` in the `addScheme` method here:  https://github.com/eclipse/microprofile-open-api/blob/bd7706d3bacfc15e8253978b75348f54df1b232f/tck/src/main/java/org/eclipse/microprofile/openapi/tck/ModelConstructionTest.java#L865  However I think null scopes should be allowed in this case, since the scheme might not support scopes **or** the user might not need any scopes to access the operation(s).

**Comment by jmini** [comment]
As discussed on gitter, I will have a look at 2 and 3
