### ISSUE TITLE
The Scopes class should be deprecated (similar to ServerVariables)

### ISSUE THREAD

**Issue by EricWittmann** [eclipse/microprofile-open-api#328]
The `Scopes` class seems to be a leftover from OpenAPI 2.0.  The 3.0 specification does not have a `Scopes` object.

OpenAPI 2.0: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#scopesObject
OpenAPI 3.0: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#oauth-flow-object

In 3.0 `scopes` is a simple **Map** property of the `OAuth Flow` object.  As a result it is not extensible and should be modeled as a simple map in MP+OAI.

**Comment by arthurdm** [comment]
I agree - and there's a good example inside `SecurityRequirement` on how to store a scope without needing a new class.

**Comment by jmini** [comment]
This is fixed with PRs:

* #345, targets the 2.0 branch, is allowed to break the API and remove interfaces/methods
* #346, targets the 1.x branch, where you have deprecations in a non-breaking way.

Feel free to reopen if you disagree.
