### ISSUE TITLE
Parameters annotation should only target the method

### ISSUE THREAD

**Issue by arthurdm** [eclipse/microprofile-open-api#340]
Current our [Parameters annotation](https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/annotations/parameters/Parameters.java#L33) has two targets: method and parameter.

@arturdzm brought up a good point that it should only have the method target.  Otherwise, if we associate `@Parameters` with a single parameter, we're associating `multiple` parameters with a single one..which doesn't make much sense.

**Comment by arthurdm** [comment]
PR https://github.com/eclipse/microprofile-open-api/pull/352 has completed the development work piece of this issue.  However, we're still missing the corresponding TCK update.  At the moment the TCK should not complile.

**Comment by EricWittmann** [comment]
@arthurdm This seems complete now with https://github.com/eclipse/microprofile-open-api/pull/358 ?

**Comment by arthurdm** [comment]
agreed.  closing.
