### ISSUE TITLE
Create release note on the spec

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-open-api#343]
The open api spec does not have the release note section. Please add the section and list what changed for 1.1 and 2.0. Please refer to config spec for an example.

**Comment by arthurdm** [comment]
Thanks Emily.  We do have https://github.com/eclipse/microprofile-open-api/blob/master/spec/src/main/asciidoc/release_notes.asciidoc, but unfortunately it wasn't updated in the 1.1 release.   This workitem should fix that.

**Comment by jmini** [comment]
I think this issue was fixed by #353 and #354. I am closing it now, feel free to reopen it if needed.
