### ISSUE TITLE
Name attribute missing from Schema interface

### ISSUE THREAD

**Issue by MikeEdgar** [eclipse/microprofile-open-api#347]
The `org.eclipse.microprofile.openapi.annotations.media.Schema` annotation defines a `name` attribute for the purpose of naming the schema or property to which the annotation is attached. However, there is no such property on the `org.eclipse.microprofile.openapi.models.media.Schema` interface to allow for programmatic retrieval or setting of the name attribute.

I was not able to find any previous issues or discussion as to why it would be missing in the interface. Is this an intended omission?

**Comment by MikeEdgar** [comment]
After some further study of the API, it has become obvious that the name is not a part of the `Schema` interface because the name is held as the key in the `Map.Entry` where the `Schema` is the value.

That is -
```java
@Schema(name = "foo")
private Foo field;
```

Becomes - 
`Map.Entry<String, Schema>` where the key is "foo" and the value is an instance of the `Schema` interface.

**Comment by EricWittmann** [comment]
You are right of course, but I seem to recall we had some discussion that the names of some of these indexed elements might be available on the entities themselves.  Am I mis-remembering, or did we decide against that?  @arthurdm @jmini

**Comment by arthurdm** [comment]
ya, I think we chatted about this during `PathItem` maybe?  Although for that scenario it was a bit different because the `path` was actually something very useful to know at the model level because it was the URL.  

In this case, would it be helpful for a `Schema` model to know its name?

**Comment by EricWittmann** [comment]
I think this is useful information internally but perhaps not as part of the API.  @MikeEdgar - am I correct that you are casting to the smallrye impl to determine the name?

**Comment by MikeEdgar** [comment]
@EricWittmann - that's correct about casting the impl class.

**Comment by EricWittmann** [comment]
OK that's probably fine for that use-case then.
