### ISSUE TITLE
Is it intended to break backward compatibility in 1.1 for model API?

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile-open-api#350]
1.1 breaks the backward compatibility at several levels, the addExtension breakage is likely acceptable in current state - not much libraries using this API and in user land it just requires a new compilation - but the fact to prevent to use the map inherited method (APIResponses etc) is impacting directly the user who was able to manipulate the model this way.

Was it intended to impact the user that hard? It requires to rewrite potentially a lot of code.

Romain

**Comment by EricWittmann** [comment]
Can you send a github link of the diff you're talking about?  The `Map` interface for `APIResponses` wasn't changed from 1.0 to 1.1 afaik.

**Comment by rmannibucau** [comment]
@EricWittmann the addX(key, null) methods are now enforced to ignore the add whereas it was not before, there are also numerous new getters which has impacts on the serialization when not using built-in serializer (out of /openapi endpoints). Both changes are breaking existing code base AFAIK.

**Comment by arthurdm** [comment]
hey @rmannibucau - can you please send us a link to the 1.0 vs 1.1 particular github diff you are having troubles with?

**Comment by rmannibucau** [comment]
@arthurdm I think it was https://github.com/eclipse/microprofile-open-api/commit/b29a98a75e0c911c373184e857f8b1da179e9536#diff-c0f0514ec010cae8a91e4016952017cc for instance. I also notice some new getters and therefore a difference in serialization of OpenAPI instance compared to a serializer set up for 1.0 which impacts users.

**Comment by EricWittmann** [comment]
But that is a 2.0 change, not a 1.1 change.  You can see the definition of that class in 1.1 here:

https://github.com/eclipse/microprofile-open-api/blob/1.x/api/src/main/java/org/eclipse/microprofile/openapi/models/responses/APIResponses.java#L31

Your original indicates that 1.1 breaks backward compatibility, which would be bad.  But it's OK if 2.0 breaks it.

**Comment by arthurdm** [comment]
Thanks guys. Seems that we're all good since the `1.1` -> `2.0` changes are expected, and allowed.
