### ISSUE TITLE
Define default values for required property per parameter type

### ISSUE THREAD

**Issue by neon-dev** [eclipse/microprofile-open-api#355]
I couldn't find much info about query parameter handling in the spec. This example already suggests, it could be an optional parameter and I would agree: https://github.com/eclipse/microprofile-open-api/blob/master/spec/src/main/asciidoc/microprofile-openapi-spec.adoc#requestbody
However some implementors set them required by default, just like `@PathParam` or `@FormParam` (where it's fine).
As discussed in https://github.com/smallrye/smallrye-open-api/issues/110 one could consider defining requirements in the spec for each possible parameter type.

**Comment by neon-dev** [comment]
Seems like the default behavior is defined in the OpenAPI spec itself:
> There was also a question in this thread (@neon-dev) regarding non-required params. I think the behavior you're seeing is fixed, but just not yet released. It looks like the OpenAPI spec does define the default requirements for parameters, which aligns with what you were thinking: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#parameterObject

_Originally posted by @MikeEdgar in https://github.com/smallrye/smallrye-open-api/issues/110#issuecomment-496889704_  

This is the relevant part:
> If the parameter location is "path", this property is **REQUIRED** and its value MUST be true. Otherwise, the property MAY be included and its default value is false.

**Comment by EricWittmann** [comment]
We discussed this issue in today's hangout.  Here is what we have (tentatively?) decided to do:

* No changes will be made to the **text** of the Microprofile OpenAPI specification
* The TCK will be updated to ensure that Query parameters are not set as **required** by default

To be clear, the TCK will not assert that the `required` property for query parameters is **false**.  Instead, it will assert that the `required` property for a query parameter is either **not present** or **present and false**.

We will also update the TCK to make sure that query parameters can be marked as **required** by using a separate OpenAPI annotation to explicitly set that property value.

Also note - these same rules will apply to **cookie** and **header** parameters as well.

**Comment by EricWittmann** [comment]
If there are any concerns about this, or you think we messed up, please follow up here asap. :) @neon-dev 

I should add that the text of the specification isn't very explicit about how to process Jax-rs annotations, and we'd generally like to keep it that way.  The TCK is how certain annotation processing expectations are asserted.

**Comment by neon-dev** [comment]
I'm totally fine with this, thanks :)

**Comment by neon-dev** [comment]
So will an issue be necessary in the SmallRye implementation for JAX-RS annotation handling or is it already on your list?
If I understand it correctly the TCK ensures that implementors follow the spec, but it doesn't cover these annotations, so introducing/keeping inconsistent behavior here is allowed (but why would anyone want to?).

**Comment by EricWittmann** [comment]
If the smallrye impl is setting `required` to *true* for query params (and others like cookie and header) then we should add an issue there and get it resolved.

**Comment by neon-dev** [comment]
Glancing over the source code on GitHub it looks like it already handles that correctly:
https://github.com/smallrye/smallrye-open-api/blob/e29bdabc89aae81e00be32cdb4dd5a34f551f6c2/implementation/src/main/java/io/smallrye/openapi/runtime/scanner/OpenApiAnnotationScanner.java#L555
I'm currently on vacation so I don't have a project at hand were I experienced this. I'll create an issue in a week or two when I can verify this behavior.
