### ISSUE TITLE
Questions on several TCK test cases on parameters

### ISSUE THREAD

**Issue by MikeEdgar** [eclipse/microprofile-open-api#357]
1. `AirlinesAppTest.testContentExampleAttribute` checks for the `example` string for the `airlines` parameter of [ReviewResource.getReviewByAirlineAndUser](https://github.com/eclipse/microprofile-open-api/blob/0c7c8f23f50fb15ffea8f0d47989b898859ba1e1/tck/src/main/java/org/eclipse/microprofile/openapi/apps/airlines/resources/ReviewResource.java#L323). However, the `@Parameter` definition is nested in a `@Parameters` on the first method argument. I see issue #340 related to this. Is there any possibility of changing this test case prior to 2.0?

2. ~~`AirlinesAppTest.testContentInParameter` tests for the presence of a schema type in the content attribute on method [ReviewResource.getReviewByUser](https://github.com/eclipse/microprofile-open-api/blob/0c7c8f23f50fb15ffea8f0d47989b898859ba1e1/tck/src/main/java/org/eclipse/microprofile/openapi/apps/airlines/resources/ReviewResource.java#L229). Is this correct? I do not see what the schema would be generated from.~~

3. ~~`AirlinesAppTest.testParameter` tests (via `AirlinesAppTest.testReviewIdMethods`) for the presence of a schema type in the content attribute (similar to 2) on method [ReviewResource.getReviewById](https://github.com/eclipse/microprofile-open-api/blob/0c7c8f23f50fb15ffea8f0d47989b898859ba1e1/tck/src/main/java/org/eclipse/microprofile/openapi/apps/airlines/resources/ReviewResource.java#L192). Same question as 2, is this correct?~~

*Edit*: Disregard 2 and 3. I overlooked that `@Parameter#content` and `@Parameter#schema` are mutually exclusive.

**Comment by arthurdm** [comment]
Thanks @MikeEdgar - ya, it definitely feels weird to check for an example of `airlines` from within the `@Parameters` definition from `user`.  We will discuss this at tomorrow's hangout.   Although we could change the TCK, prior to `2.0` this would still be a valid scenario as per the spec.

**Comment by arthurdm** [comment]
I confirmed that the TCK for the `2.0` branch has been updated, and I believe the decision in the last hangout was to not change this in the TCK for 1.x as (although not very intuitive) it is legal.  Closing this, please re-open if needed. :)
