### ISSUE TITLE
Create a sample of the OASModelReader

### ISSUE THREAD

**Issue by arthurdm** [eclipse/microprofile-open-api#36]
This sample should showcase how an app dev would contribute a model tree (either complete or partial), using the `OASModelReader`.

Here's an example from the Swagger repositories on a similar approach: https://github.com/microservices-api/oas3-configuration/blob/master/sample.oas.programmingModels/src/io/swagger/sample/config/OpenAPIConfigurationImpl.java#L23

**Comment by navidsh** [comment]
@leochr and @a-saf are working on this issue.

**Comment by a-saf** [comment]
Merged PR #157 contains the sample of OASModelReader implementation for airlines app

**Comment by arthurdm** [comment]
Closing - will be finished via https://github.com/eclipse/microprofile-open-api/issues/215
