### ISSUE TITLE
Properties can not be defined in @Schema

### ISSUE THREAD

**Issue by jmini** [eclipse/microprofile-open-api#360]
@agiertli asked on Gitter (Jun 24 15:28) following question:

----

Hi folks,

I am trying to annotate a parameter which holds an uploaded file in my POST request:

The final OpenAPI spec should look like this:
https://swagger.io/docs/specification/describing-request-body/file-upload/

```yaml
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                fileName:
                  type: string
                  format: binary
```

I can't seem to find a suitable way how to define 'properties'., when using MicroProfile annotations for OpenAPI. So far, I have this:

```java
public Response processInvoice(
        @RequestBody(content = @Content(mediaType = "multipart/form-data", schema = @Schema(type = SchemaType.OBJECT))) MultipartFormDataInput input)
```

Which generates:

```yaml
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
```

So it seems I am on the right track, but not sure how to proceed further..any ideas?

**Comment by jmini** [comment]
My idea back then was:

Yes it seems to me that you are right the [`@Schema`](https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/annotations/media/Schema.java) annotation do not let you define any properties as member.

A way to achive this, could be that you create a reference to an other object.

```yaml
      requestBody:
        content:
          multipart/form-data:
            schema:
                $ref: '#/components/schemas/MyRequestBody'
```

With a component section being like this:

```yaml
components:
  schemas:
    MyRequestBody:
      description: TODO
      type: object
      properties:
        fileName:
          type: string
          format: binary
```

From an OpenAPI point of view the indirection over the components section is semantically the same.

And then to create the `MyRequestBody` object in the schemas section of the components section:

* either you have it defined in a static file (without the paths that will be populated by annotation scanning)
* or you implement a `OASModelReader` that create your additional schemas in the `buildModel() method

Instead of sharing the schema in the component section you can even share the complete "request body" section

---

I think `@Schema` could provide a way to set properties directly.

**Comment by EricWittmann** [comment]
I think that a fairly simple solution to this (and perhaps one that is not controversial) would be to introduce `properties` to the `@Schema` annotation.  So for example, an application of the `@Schema` annotation might look like this:

```java
@Schema(properties={
    @Schema(name="creditCard", required=true),
    @Schema(name="departtureFlight", description="The departure flight information."),
    @Schema(name="returningFlight")
})
```

This would allow the developer to describe any properties at all.

**Comment by jmini** [comment]
I think this is a good idea.

**Comment by MikeEdgar** [comment]
I really like this idea and it mirrors the `Schema` programmatic interface, but I don't think annotations can reference themselves, unfortunately. We briefly spoke about having something like `@SchemaType` and `@SchemaProperty` that split out the fields of the current `@Schema` annotation. Obviously that would be a major change from the current API.

**Comment by EricWittmann** [comment]
Rats - you are right.  No cycles allowed in java annotations.  So yeah, we would need to have a new annotation called `@SchemaProperty` that duplicated much (all) of what is currently in `@Schema`.  That's probably not the end of the world, but because annotations also cannot extend anything (IIRC) there's no way to share the properties.

**Comment by MikeEdgar** [comment]
Yes, I think you're right. That then introduces some other design decisions such as: does `@Schema` usage on fields, methods, and parameters needs to be restricted in favor of using the new annotation in those locations?

**Comment by EricWittmann** [comment]
If only an annotation could extend another one, I think this decision would be easier.  To answer your question, and without thinking too deeply about this, `@Schema` usage on fields and methods both (I think) are meant to describe a schema property.  Not sure about parameters though.  

But yeah, in general you are right - if we added an `@SchemaProperty` annotation, we should think about the appropriate application of each.  i.e. which one should be allowed where.

**Comment by arthurdm** [comment]
hey guys.  after thinking more about this, I am leaning towards the `do nothing` answer due to Java's annotation cycle restriction - for example, even if we had something like `@SchemaProperty`, that would only allow a Schema with a single depth of properties to be defined, which would prevent other more complex / composed Schema to be defined purely with the annotations.  

I think if someone doesn't want to create POJOs (which IMO is the best practice), or doesn't want to keep a static file snippet, they can use the `OASModelReader` to create things in Java programmatically.

**Comment by EricWittmann** [comment]
That's a reasonable position, I think.  Not sure if I agree or not - will need to consider.  :)  I've left this as a hangout topic for discussion at the next meeting.

**Comment by MikeEdgar** [comment]
Although it would be limited to a single depth of properties, I think something like `@SchemaProperty` would still allow for a full definition of a schema structure when used within `@OpenAPIDefinition`/`@Components`. Granted, applications would need to use either `ref` or `implementation` to achieve that, but it would be supported with annotations only.

**Comment by arthurdm** [comment]
Looks like we're proposing something like this (taken from Eric's snippet)

```
@Schema(properties={
    @SchemaProperty(name="creditCard", required=true),
    @SchemaProperty(name="departureFlight", description="The departure flight information."),
    @SchemaProperty(name="returningFlight")
})
```

**Comment by arthurdm** [comment]
I agree with the above proposal

**Comment by arthurdm** [comment]
Doesn't look like we have any objections, so let's put this into plan for `2.0.`  🎉

**Comment by MikeEdgar** [comment]
@arthurdm - I did not have a properly formatted comment in the PR :-). I believe this should have been closed by #384.

**Comment by arthurdm** [comment]
awesome.  closing this.  thanks @MikeEdgar!

**Comment by phillip-kruger** [comment]
@jmini - I am looking to create the release notes for 2.0. Not sure why this has been marked as a incompatible change ? From what I can see (@MikeEdgar please confirm) then change is backward compatible. Current users would not need to make any changes to upgrade (w.r.t to this). There is just a new property available on `@Schema`

**Comment by MikeEdgar** [comment]
@phillip-kruger , I agree - unless there is some additional meaning the label is meant to convey.
