### ISSUE TITLE
Streamline annotating a method's @Response when using JAX-RS Response object

### ISSUE THREAD

**Issue by EricWittmann** [eclipse/microprofile-open-api#363]
Originally posted in SmallRye here:  https://github.com/smallrye/smallrye-open-api/issues/76

Content copy/pasted from source:

---

OpenApi has an [ApiResponse annotation](https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/annotations/responses/APIResponse.java) which, via its nested Content, can provide the information about the JAX-RS Response entity class.

While this annotation covers well for a case where Response dynamically sets different entity types per the current response media type, it is too complex for a typical case of Response returning a known single entity type only, with @Produces already typing a response media type.

One proposal is to have something like this:
```java
@Produces("application/json")
@ApiResponseType(MyType.class)
@GET
public Response get() { return Response.ok(new MyType()).build(); }   
```
but other options should also be considered

**Comment by EricWittmann** [comment]
We should first try to leverage existing annotations if possible.  Perhaps the `@Response` annotation can be used here.

**Comment by arthurdm** [comment]
Thanks for opening this up.  

What if we put words around `@ApiResponse` that said:  if the `mediaType` property is not specified (or is empty) it inherits from the method's `@Produces`.   So then it would be an error if `mediaType` is empty and either: (a) no `@Produces` is present, (b) more than one `@Produces` is present.  

The reasoning behind this is:  while `@Produces` and `mediaType` are duplicates there are other parts of `@Content` (example, examples, encoding) that could still apply?

**Comment by MikeEdgar** [comment]
I definitely agree with using the `@Produces` value if none is specified, but I would rather have it default to `*/*` if completely missing or if there are multiple instead of producing an error. 

I see this issue as allowing something like this:

```java
@ApiResponse(MyResponseClass.class)
```
as a simpler alias of the verbose current state:
```java
@ApiResponse(content = @Content(schema = @Schema(implementation = MyResponseClass.class)))
```

Side note: if a change is made for `@ApiResponse` I think that `@RequestBody` should also be updated to align.

**Comment by arthurdm** [comment]
Maybe `@SimpleResponse` and `SimpleRequest`?

**Comment by EricWittmann** [comment]
I agree as well - we just need to finalize the naming.  :)

**Comment by MikeEdgar** [comment]
Assuming everyone agrees this should be a new annotation and not a modification to `ApiResponse` and `@RequestBody`, how about the following (to keep the naming in alignment with existing objects). Whether or not there are additional attributes besides `value` (status code?), also needs to be determined.

```java
@ApiResponseSchema(value = MyResponse.class)
@RequestBodySchema(value = MyRequest.class)
```

**Comment by arthurdm** [comment]
I like those names @MikeEdgar, +1

My suggestion is to keep these new annotations very simple, with just the single field (Pojo ref).  For anything else, such as setting multiple responses based on status code, the user would then utilize `@APIResponses` & `@APIResponse`.

**Comment by MikeEdgar** [comment]
Sounds good to me.

**Comment by arthurdm** [comment]
awesome.   this is now into `2.0` plan. =)   thanks for driving this guys.

**Comment by MikeEdgar** [comment]
I started to add these changes in my fork in branch [363_simplified_request_response](https://github.com/MikeEdgar/microprofile-open-api/tree/363_simplified_request_response) - here is the [link to compare](https://github.com/eclipse/microprofile-open-api/compare/master...MikeEdgar:363_simplified_request_response). Before I go further with anything in the spec doc or TCK, feedback and comments are welcome to make sure this is what the group wants. 

Please note that I did add some details around how status codes and descriptions should be determined for `@APIResponseSchema`. This is based on a discussion in smallrye/smallrye-open-api#100 that I believe should apply generally for portability purposes, but that has yet to be agreed to in this issue.

**Comment by MikeEdgar** [comment]
We still need some discussion on how the responseStatus and description properties (that are both required in `@APIResponse`) should be handled for the new simplified response annotation. The initial JavaDoc I worked on defined rules about how they are generated in the output based on logic in SmallRye, but that may be too restrictive and/or limit the value of at least the annotation.

Suggestion
1. `@RequestBodySchema` contains simply `Class<?> value()`
2. `@APIResponseSchema` contains:
- `Class<?> value()`
- `String description() default ""`
- `String responseCode() default "default"`

Without those two additional properties for the response, I think the spec needs to include some definition of what will be generated, either based on what is done in SmallRye or something new.

**Comment by EricWittmann** [comment]
Seems like a reasonable suggestion to me.  (2) is slightly confusing since the description property is actually for the response and not the schema (schemas can have descriptions too).  But I think that's really nitpicking - the utility of the new annotation should make it more clear what's going on, especially in light of the `responseCode` property (which is obviously an APIResponse thing and not a Schema thing).

**Comment by EricWittmann** [comment]
That said, I've added this as a hangout topic - so we can talk about it on the next call.

**Comment by MikeEdgar** [comment]
Minor update to the earlier suggestion - `description` has become `responseDescription`.

1. `@RequestBodySchema` contains:
    -  `Class<?> value()`
2. `@APIResponseSchema` contains:
    - `Class<?> value()`
    - `String responseDescription() default ""`
    - `String responseCode() default "default"`
