### ISSUE TITLE
Sort order during document generation

### ISSUE THREAD

**Issue by EmirAde** [eclipse/microprofile-open-api#365]
Hi,

I'm currently using microprofile-openapi-api v1.1.2. The sorting order is not the same as the order of the variables within my annotated POJO, when generating the OpenAPI document. Is there a way to have the same order?

I know there is already a discussion about custom ordering, however is there some sort of global setting I'm missing?

This is my first issue, sorry for inconsistencies.

Best Regards
Emir

**Comment by EricWittmann** [comment]
What implementation of the specification are you using?

**Comment by arthurdm** [comment]
I agree with @EricWittmann - we don't have a global setting, and to be honest, that would be very hard to do given how different implementations work today.  What we could do is allow for ordering per POJO, which is issue #359.

**Comment by arthurdm** [comment]
Closing this one due to inactivity and based on the fact we're discussing it in a few other issues.  @EmirAde - please feel free to re-open if you would like to chat about this more.
