### ISSUE TITLE
Nested Lists annotation

### ISSUE THREAD

**Issue by EmirAde** [eclipse/microprofile-open-api#367]
Hi,

is it possible to annotate a nested array with @Schema? 

Example:
`private List<List<String>> configurations;`

The resulting json should be like this:
```
"configurations": {
   "description": "Some description",
   "type": "array",
   "items": {
      "type": "array",
      "items": {
         "type": "string"
      }
   }
}
```

**Comment by MikeEdgar** [comment]
@EmirAde - it may be possible depending on the implementation. For example, the following should work if you are using the SmallRye implementation.

```java
@Schema(implementation = String[].class, type = SchemaType.ARRAY)
private List<List<String>> configurations;
```

**Comment by EmirAde** [comment]
@MikeEdgar Thanks for the help. Unfortunately we use the following (enforced by client):

```
<groupId>org.eclipse.microprofile.openapi</groupId>
      <artifactId>microprofile-openapi-api</artifactId>
<version>1.0.1</version>
```

Your example did not work though. Is there a way with the implementation I use?

**Comment by MikeEdgar** [comment]
@EmirAde - which server are you using? E.g. Thorntail, Open Liberty, Quarkus, etc.?

**Comment by EmirAde** [comment]
I use Payara v5.184

**Comment by MikeEdgar** [comment]
@EmirAde - you might ask at the [Payara repository](https://github.com/payara/Payara). The OpenAPI spec supports declaring the nested array, but different implementations may vary.

**Comment by EmirAde** [comment]
All right, I'll do that, thank you.
