### ISSUE TITLE
Read the test.url property for TCK in BeforeClass instead of BeforeSuite?

### ISSUE THREAD

**Issue by jmartisk** [eclipse/microprofile-open-api#368]
With Quarkus, we hit a problem with the OpenAPI TCK, because we support setting a random HTTP port to bind the testing container to, in which case the actual HTTP port is not known in advance, so we are unable to pass it using the `test.url` property from command line - instead, the testing framework sets the `test.url` property during boot of the container, but that's too late for a `@BeforeSuite` callback (https://github.com/eclipse/microprofile-open-api/blob/1.1.2/tck/src/main/java/org/eclipse/microprofile/openapi/tck/AppTestBase.java#L46) to be able to see it. We'd like to move the RestAssured configuration code to a `@BeforeClass` callback instead, that runs late enough. 

Yes that means it will be run multiple times, but the contents of the `@BeforeSuite` method are idempotent so it shouldn't probably matter - with the exception of the `RestAssured.filters()` call - that would be moved to a new `@BeforeSuite` callback.

See https://github.com/quarkusio/quarkus/issues/4211 for more context

**Comment by jmartisk** [comment]
I'm a bit confused about the branches in this repo, what's currently the difference between `2.0` and `master`? Both declare `2.0-SNAPSHOT` version in pom.xml but contain different commits, that doesn't sound right.

If I want to get this into a 1.1.3 soon, I see that `1.x` branch now targets 1.2 - is there still a branch for 1.1.x minor updates?

**Comment by arthurdm** [comment]
hey @jmartisk - sorry for the delay in responding.   Our goal is that the next release will be 2.0, so that's why our master is now declaring `2.0-SNAPSHOT`.  We can probably clean up the branches to remove the duplicate ones.   

I would try to avoid a `1.x` release unless there's a very good reason, like a bug or something like that - to try to load up `2.0` as much as possible and help push that forward.

**Comment by jmartisk** [comment]
Okay I'll send a PR with this to master only
