### ISSUE TITLE
how to generate description for object type parameter

### ISSUE THREAD

**Issue by violin0631** [eclipse/microprofile-open-api#372]
I am using microprofile-openapi-api ver 1.1.2 to generate API document.
The source code for the API as follows (Kotlin language)

```
@POST
@Operation (summary = "SUMMARY", description = "DESCRIPTION", operationId = "getData")
fun getData (
@Parameter (description = "PARAMETER DESCRIPTION", required = true)
req: DataRQ): DataRS {
return service.getData (req)
}
```

However, with this source code, we are not generating the description for the parameter.
But if change DataRQ type to String, the description of the parameter is generated successfully

So in this case, if the parameter is an object, how to setting @Parameter to be able to generate a description for parameter.

**Comment by MikeEdgar** [comment]
@violin0631 , what is the type of the parameter? E.g. `@PathParam`, `@QueryParam`? That should be specified as well.

**Comment by violin0631** [comment]
@MikeEdgar  Type of the parameter is not `@PathParam`, `@QueryParam`. I want to set  `body`.
How to set the type of parameter is `body`. Is there any way to do this?

**Comment by EricWittmann** [comment]
Microprofile OpenAPI only supports OpenAPI version 3.  One of the changes between version 2 and 3 is that the body is no longer considered a parameter.  Operations now have a new "request body":  https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#operationObject

So in this case applying a `Parameter` annotation will not have any effect.  Instead, you probably want to apply a `RequestBody` annotation:

https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/annotations/parameters/RequestBody.java

You can put it on the method argument or on the method itself.  Either way **should** work.  Might be implementation dependent.  So if one doesn't work, try the other (and report a bug).  :)

**Comment by violin0631** [comment]
@EricWittmann  Thanks for replying.
In OpenApi v3, if the api argument is an object, the api document will generate requestBody, not the parameter. I understand. I will close this issue
