### ISSUE TITLE
Open API does not permit the same path/HTTP method more than one time.

### ISSUE THREAD

**Issue by rhuan080** [eclipse/microprofile-open-api#375]
Hi,

I have seen microprofile-open-api does not show all path/ HTTP methods when I have two methods with the same path and HTTP method. Look this example.

```
  @PATCH
    @Path("{id}")
    @Consumes(value={"image/jpeg","image/png"})
    @Produces(MediaType.APPLICATION_JSON)
    public Response uploadPhoto(@PathParam("id") Long id, File file, @Context HttpServletRequest httpServletRequest) throws IOException {
           // code
    }

    @PATCH
    @Path("{id}")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    public Response enableUser(@PathParam("id") Long id, @QueryParam("code") @NotEmpty String code) throws IOException {
         // code
  }

```

The output is:

```
openapi: 3.0.1
info:
  title: Generated API
  version: "1.0"
paths:
 /users/{id}:
    patch:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/Long'
      requestBody:
        content:
          image/jpeg:
            schema:
              $ref: '#/components/schemas/File'
          image/png:
            schema:
              $ref: '#/components/schemas/File'
      responses:
        200:
          description: OK
          content:
            application/json: {}
```
Note that the methods have different Consumes and it works in JAX-RS. Then it should show two calls using PATCH method.

**Comment by rhuan080** [comment]
I have seen the Microprofile classes and it seems to be a problem in these interface:

org.eclipse.microprofile.openapi.models.Paths.java
org.eclipse.microprofile.openapi.models.PathItem.java

The PathItem expect a single object of Operation to each HTTP method. look it:

```
public interface PathItem extends Constructible, Extensible<PathItem>, Reference<PathItem> {
    ...
    Operation getGET();

    void setGET(Operation var1);

    ...
    Operation getPUT();

    void setPUT(Operation var1);

    default PathItem PUT(Operation put) {
        this.setPUT(put);
        return this;
    }

    Operation getPOST();

    void setPOST(Operation var1);

    default PathItem POST(Operation post) {
        this.setPOST(post);
        return this;
    }

    Operation getDELETE();

    void setDELETE(Operation var1);

    default PathItem DELETE(Operation delete) {
        this.setDELETE(delete);
        return this;
    }

    Operation getOPTIONS();

    void setOPTIONS(Operation var1);

    default PathItem OPTIONS(Operation options) {
        this.setOPTIONS(options);
        return this;
    }

    Operation getHEAD();

    void setHEAD(Operation var1);

    default PathItem HEAD(Operation head) {
        this.setHEAD(head);
        return this;
    }

    Operation getPATCH();

    void setPATCH(Operation var1);

    default PathItem PATCH(Operation patch) {
        this.setPATCH(patch);
        return this;
    }

    Operation getTRACE();

    void setTRACE(Operation var1);

    default PathItem TRACE(Operation trace) {
        this.setTRACE(trace);
        return this;
    }

    /** @deprecated */
    @Deprecated
    default List<Operation> readOperations() {
        return (List)this.getOperations().values().stream().collect(Collectors.toList());
    }

    /** @deprecated */
    @Deprecated
    default Map<PathItem.HttpMethod, Operation> readOperationsMap() {
        return this.getOperations();
    }

    Map<PathItem.HttpMethod, Operation> getOperations();

    List<Server> getServers();

    void setServers(List<Server> var1);

    default PathItem servers(List<Server> servers) {
        this.setServers(servers);
        return this;
    }

    PathItem addServer(Server var1);

    void removeServer(Server var1);

    List<Parameter> getParameters();

    void setParameters(List<Parameter> var1);

    default PathItem parameters(List<Parameter> parameters) {
        this.setParameters(parameters);
        return this;
    }

    PathItem addParameter(Parameter var1);

    void removeParameter(Parameter var1);

    public static enum HttpMethod {
        POST,
        GET,
        PUT,
        PATCH,
        DELETE,
        HEAD,
        OPTIONS,
        TRACE;

        private HttpMethod() {
        }
    }
}
```
I think it should be a List.

**Comment by MikeEdgar** [comment]
@rhuan080 , the API does support different media types at the same path and HTTP method. I suspect the behavior you're seeing is vendor/version specific. What server and version are you using?

Also, your example does point out something that is NOT supported - parameters that are specific to a media type. The JSON consuming `PATCH` method is shown with a query parameter whereas the image method does not have one. Parameters are defined at either the path or the HTTP method level, not at the request body level which is where the media type differentiation occurs.

**Comment by rhuan080** [comment]
@MikeEdgar I'm using Thorntail, but it happens with other vendors as well.

I disagree my example does point out something that is NOT supported. _Parameters that are specific to a media type_ works with JAX-RS and I'm able to make tests using Postman, curl or any tools that make HTTP request. My question is only with OpenApi. 

I think this behavior is not specific to vendor. I think the problem is in the org.eclipse.microprofile.openapi.models.PathItem.java. I'm applying  some updates (in SmallRye and Microprofile-open-api) in my local environment. In case of a confirmation that  _Parameters that are specific to a media type_  is supported by JAX-RS, I can send a pull request. I think the main questions is: Is this feature (_ parameters that are specific to a media type_) supported by JAX-RS? I think so.

**Comment by MikeEdgar** [comment]
@rhuan080 , I agree that parameters that are specific to a media type is something supported by JAX-RS. I don't believe it is supported by the OpenAPI specification, however. 

Regarding a list/array of operations for a path and HTTP method, that is not supported by OpenAPI. Please refer to the documentation on [Paths and Operations](https://swagger.io/docs/specification/paths-and-operations/). The part that is relevant is stated under the "Operations" heading:

> OpenAPI defines a unique operation as a combination of a path and an HTTP method. This means that two GET or two POST methods for the same path are not allowed – even if they have different parameters (parameters have no effect on uniqueness)

What you are trying to do can be accomplished (except the query parameter) with different media types nested under the operation, but as I said if that is not working it is probably due to the version being used in Thorntail. Are you using Thorntail current or an older version? This scenario was fixed a few months back in the SmallRye implementation which is used by Thorntail.

**Comment by rhuan080** [comment]
@MikeEdgar thank you for clarifications. I'm using the current version of Thorntail. Thus it is not a Microprofile or Thorntail issue. It is a limitation of OpenAPI specification.

**Comment by MikeEdgar** [comment]
@rhuan080 , based on the version of Thorntail you are using, multiple methods for the same path and HTTP method but with different media types should work with SmallRye. I believe the reason you are not seeing `application/json` in the `content` list for the `requestBody` is due to the fact that the JSON endpoint method does not define a method argument that the scanner selects for the request schema - it only has a `@PathParam` and a `@QueryParam`. You might try to add an `@RequestBody` annotation to that method for it to appear in your OpenAPI document.

**Comment by rhuan080** [comment]
Hi,

I have use the @RequestBody and I had the same results. Look this example.

```
@PATCH
    @Path("{id}")
    @Consumes(value={"image/jpeg","image/png"})
    @Produces(MediaType.APPLICATION_JSON)
    public Response uploadPhoto(@PathParam("id") Long id, @RequestBody(content = @Content(mediaType = "image/jpeg")) File file, @Context HttpServletRequest httpServletRequest) throws IOException { ...}
```
I think it does not work with SmallRye because the org.eclipse.microprofile.openapi.models.Paths.java make the associate of a path to only one org.eclipse.microprofile.openapi.models.PathItem.java. Ex.: "/user" -->PathItem.
The PathItem has an operator to each HTTP method. Thus, one path (like "user") can be associated to only one PathItem that has one Operator to each HTTP method.

But now my question is... As the OpenAPI specification does not support it, Should SmallRye support it?

**Comment by MikeEdgar** [comment]
@rhuan080 , what I was thinking is that there is no `"application/json"` entry under `requestBody`/`content` because the `enableUser` method does not have a `@RequestBody` and none of the parameters can be interpreted as one.

**Comment by arthurdm** [comment]
I agree with the limitation statement.

at first I thought:  shouldn't the second method's `JSON` consumes just be another item in the generated `requestBody.content` array, since it can contain its own Schema child?   While that would solve the problem for the `input`, it doesn't seem like OAS3 provides a way for you to distinguish the `output` - for example, if the two methods define a different response for a `200` status code, how would we model this?

**Comment by MikeEdgar** [comment]
Taking a step back, I don't know if supporting something like this in OAS would be a good fit. The semantics of having a URI operating on different things based on the media type of the request/response seems a bit confusing and is likely an API design issue. 

The idea behind REST is that a URI points to a resource and the content/media types are simply the different ways that resource can be represented/serialized. Generally speaking, the parameters for a given operations (URI + HTTP method) should not differ based on the representation of the resource.

**Comment by MikeEdgar** [comment]
This issue was discussed at the 1/9/2020 Open API Hangout. It was agreed that the example Java API definition, while supported by JAX-RS, is not supported by the current version of the Open API specification.

**Comment by arthurdm** [comment]
Thanks for the summary @MikeEdgar 

@rhuan080 - thank you for bringing this up.  We'll close this issue now, given the explanation above.

**Comment by rhuan080** [comment]
Thank you so much :-)
