### ISSUE TITLE
Is it possible to flatten nested POJOs

### ISSUE THREAD

**Issue by norrman** [eclipse/microprofile-open-api#380]
Hi,
In our code base, we use specialized "string" types instead of String attributes (for validation purposes). We now want to generate OpenApi documents, but we want to flatten these specialized type into bare string attributes. This is what I tried:

     public class SimpleString {
           private final String value;
           public SimpleString(String value) {this.value = value;}
           @JsonValue public String getValue() { return value; }
    }
and

    public class GreetingMessage {
    	private final SimpleString message;
    	public GreetingMessage(@JsonProperty SimpleString message) {
    		this.message = message;
    	}
    
    	@Schema(implementation = String.class, type = SchemaType.STRING)
    	public SimpleString getMessage() { return message; }
    }

But the generated yaml still treat the _message_ attribute as an object:
 
    components:
      schemas:
        GreetingMessage:
          type: object
          properties:
            message:
               type: object

Is there any way to achive what I want?

Thanks!

**Comment by MikeEdgar** [comment]
Which run time and version are you using? E.g. Quarkus, Open Liberty, etc.

**Comment by norrman** [comment]
Wow, I thought I was posting this on the smallrye project. Anyways, it's thorntail 2.5.0 and smallrye 1.1 as far as I can tell.

**Comment by MikeEdgar** [comment]
@norrman , this issue was fixed in Smallrye since the version included with Thorntail 2.5.0. You might try to work around it until the next Thorntail release by managing your Maven dependencies to include the current Smallrye version.

**Comment by norrman** [comment]
Hi, I tried the latest 1.1.19 but still same behavior. Should I use some other annotations?

**Comment by MikeEdgar** [comment]
Can you confirm that 1.1.19 is being used? The Maven `artifactId` changed from `smallrye-open-api-1.1` to `smallrye-open-api` as well, so make sure the correct names are being excluded/included.

**Comment by norrman** [comment]
From the pom:

        <dependency>
            <groupId>io.smallrye</groupId>
            <artifactId>smallrye-open-api</artifactId>
            <version>1.1.19</version>
        </dependency>

**Comment by norrman** [comment]
FYI: It works as expected with swagger-core.

**Comment by arthurdm** [comment]
should we create a corresponding issue and move this into SmallRye's repo?

**Comment by norrman** [comment]
Good Idea. Is there a way to move the thread?

**Comment by MikeEdgar** [comment]
@norrman - I've opened smallrye/smallrye-open-api#201 to continue this discussion. Please go ahead and close this issue and we can work through this in the SmallRye repo.
