### ISSUE TITLE
Consider enhancing the filter

### ISSUE THREAD

**Issue by arthurdm** [eclipse/microprofile-open-api#381]
There's a small section in the upstream OAS3 spec that talks about security-based filtering: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#security-filtering

It may be good for us to investigate if there's anything the MP OpenAPI spec should say (or define) in terms of our own Filter.  Should there be special treatment for `Paths` and `PathItem`, either at the filter interface or via fields / annotations?

**Comment by EricWittmann** [comment]
@lamtrhieu this might be a good issue to explore.  Perhaps come up with a proposal for a future hangout?

**Comment by lamtrhieu** [comment]
@EricWittmann Thank for the info. I might have overlooked my email. Let me have a look and see if there's anything I can come up with.

**Comment by lamtrhieu** [comment]
Hi @EricWittmann 
I have tried to read the document on security filtering but I seems cannot fully understand it. Can you please help me with a concrete examples (sample class with jax-rs Path and Path Item annotation and result document after apply security filter) ?
Another question is that how can we get the authentication/authorization data? When user send request to /openapi, they need to send an oauth token?

**Comment by EricWittmann** [comment]
@arthurdm Do you have any additional thoughts on your intent here?

I think the idea is that the OpenAPI document generated may be filtered based on the identity of the user requesting it.  But currently the `OASFilter` does not have access to any authentication/authorization information.  So I presume the issue here is whether we should enhance the filter interface in some way to help implement this use-case.  That might involve making the auth credentials (if any exist) available to the filter.  Or it might involve adding a new filtering interface specific to security.  Or perhaps update the existing filter with security-specific filtering methods.

**Comment by arthurdm** [comment]
yup, @EricWittmann has the correct idea.  

With the current [filter](https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/OASFilter.java) a developer needs to know two things in order to filter based on security:
*  the type of security the operation has defined (in terms of OAS3 spec)
*  the current user being used in the call to `/openapi`

The OAS3 security information should already be accessible via PathItem -> Operation -> SecurityRequirement, so perhaps one thing to investigate is making something like the `javax.ws.rs.core.SecurityContext` object available?

**Comment by arthurdm** [comment]
This was discussed in the hangout yesterday and there were 2 concerns with this approach:

- Functionality.   With so many different ways to authenticate / authorize, it would be hard for the spec to have a method signature that covers all cases.   We thought that perhaps this is better as a filter that vendors could provide, with a signature that matched their approach to security.  

- Performance.  Having a filter that takes into account the role of the caller means this filter is called with every request.  This would be something new (the spec currently only applies the filter once), and would hinder the ability to cache responses.

I will leave this issue opened for now, but I believe the direction is to close this in the next hangout (because of the concerns above) if there aren't any objections.

**Comment by arthurdm** [comment]
Closing this as per the concerns / comments above.
