### ISSUE TITLE
Update to Jakarta EE8 APIs for MP 4.0 in Jun 2020

### ISSUE THREAD

**Issue by kenfinnigan** [eclipse/microprofile-open-api#383]

**Comment by arthurdm** [comment]
There are some sample changes for other specs in this issue https://github.com/eclipse/microprofile/issues/126

**Comment by arthurdm** [comment]
fyi @EricWittmann - since we must release with the Jarkarta update perhaps we go out with the 2.0 version we have been brewing.

**Comment by arthurdm** [comment]
This is the only workitem for the MP OpenAPI 1.2 release (milestone added).

**Comment by arthurdm** [comment]
This workitem should be applied against the `1.x` branch, which is where we'll cut the MP OpenAPI 1.2 release from.

**Comment by arthurdm** [comment]
Closing as completed.  Thanks @MikeEdgar!

**Comment by kenfinnigan** [comment]
Re-opening as we've had to push the Jakarta EE 8 update to MP 4.0 in June

**Comment by arthurdm** [comment]
Thanks @kenfinnigan .    What would be the latest date we need to release MP OpenAPI by to make it into the June MP 4.0 release?

**Comment by arthurdm** [comment]
@MikeEdgar - when you get a chance, would you be able to please also create a PR similar to #396, but targeting the `master` branch?

**Comment by kenfinnigan** [comment]
@arthurdm My guess right now is late May, but we haven't set those dates yet

**Comment by MikeEdgar** [comment]
@arthurdm , @kenfinnigan - is it still an option to release OpenAPI 1.2 with MP 3.3? The API itself does not depend on the Java/Jakarta EE APIs (it's only the TCK) so I don't know that there would be any conflict for this specification.

Besides the Jakarta dependency change, the 1.x branch contains a yet-unrelease deprecation (`Scopes` object) that has already been removed in the master branch for 2.0. If we jump straight to 2.0, that might need to be added back and deprecated in 2.0 instead.

**Comment by kenfinnigan** [comment]
No issues in an OpenAPi 1.2 for MP 3.3

Just needs to be released by Feb 4th I think

**Comment by kenfinnigan** [comment]
From a quick look, I think it only applies to the TCK.

Also need to ensure it's added with "provided" scope

**Comment by arthurdm** [comment]
thanks for bringing that up @MikeEdgar.  As we discussed in the hangout today, we'll proceed with the 2.0 release as our next train.
