### ISSUE TITLE
Extensions via Annotations

### ISSUE THREAD

**Issue by MikeEdgar** [eclipse/microprofile-open-api#387]
Annotations for models that are `Extensible` do not provide a way to list the extensions. Opening this issue for discussion in case this was not by design (I didn't see any issues about it). 

I would expect to see something like `Extension[] extensions() default {}` in each of the annotations where the equivalent model is `Extensible`.

**Comment by EricWittmann** [comment]
We all agreed that this is a good addition.  So we're going to add this.

One wrinkle that was brought up - do we ALSO remove the ability to add the `@Extension` annotation. We could change things so that the ONLY way to specify an extension is to add it as a child property of another openapi extension...

**Comment by arthurdm** [comment]
Thanks Eric.  I vote for removing the ability to use `@Extension` outside of another annotation, to avoid ambiguity.  

For example: if we added `@Extension` into a JAX-RS resource method, different users could have different expectation about which OAS3 elements that extension applied to:  is it the request, the response, the path, security scheme, all of the above?

**Comment by MikeEdgar** [comment]
+1 to only allow `@Extension` as a child of another annotation. I think that also means the wrapper annotation `@Extensions` should be pruned. One other item we discussed on this (I think :-D ) is that the TCK may be missing scenarios for extensions.

**Comment by ambition-consulting** [comment]
Is there any way, to add "x-logo", "x-favicon" or other vendor extensions to the OpenAPI spec?

**Comment by phillip-kruger** [comment]
`@Header` ?

**Comment by ambition-consulting** [comment]
How does this work with @Header? I would expect this to be in the @Info, where they also belong according to openapi specification.

**Comment by ambition-consulting** [comment]
Similarly, I don't see how - using MP annotations - I can embed references to info:description, as required by redoc:
https://redoc.ly/docs/api-reference-docs/embedded-markdown/

For reference, this is where the extension requirement comes from:
https://redoc.ly/docs/api-reference-docs/vendor-extensions/redoc-supported-extensions/#x-logo

Swagger seems to support those as well:
https://swagger.io/docs/specification/openapi-extensions/

Why restrict your users to what they can write in the tags, and not just allow extensions anywhere?

**Comment by MikeEdgar** [comment]
@ambition-consulting - as you have found, what you want to do can't be done (yet) via annotations. Your best bet with the current version of MP is to utilize the model to programmatically add the extensions. 

```java
public class ExtensionFilter implements OASFilter {
    @Override
    public void filterOpenAPI(OpenAPI model) {
        model.getInfo().addExtension("x-logo", "https://example.com/your-logo.png");
    }
}
```
This particular issue is to track the change for future releases of the specification to support using annotations for this same functionality. The use of `$ref` for arbitrary elements is also not supported, e.g. for info:description.

**Comment by ambition-consulting** [comment]
Understood, thanks for the kind explanation.

**Comment by MikeEdgar** [comment]
If done for 3.1, the current functionality of allowing `@Extension` on fields, methods, params, and types needs to be kept and deprecated.
