### ISSUE TITLE
Configuration to override the default endpoint '/openapi/ui'

### ISSUE THREAD

**Issue by genxlogics** [eclipse/microprofile-open-api#388]
Hi, I just wanted to know if there is a way to override the default api endpoint '/openapi/ui' using mpConfig or through programming model?

**Comment by arthurdm** [comment]
hi @genxlogics - The MicroProfile OpenAPI spec doesn't (yet) have any mention of an UI.  We have discussed this item ([here](https://github.com/eclipse/microprofile-open-api/issues/334)) for inclusion in our upcoming 2.0, but it would be just in terms of guidelines - not mandating the UI.

I will close this item in favour of #334.   In that issue we have agreed that implementations could make this value configurable - but doing so would mean being outside of the spec.  Feel free to add comments in that issue @genxlogics
