### ISSUE TITLE
Milestone for MP 3.3

### ISSUE THREAD

**Issue by ederks85** [eclipse/microprofile-open-api#395]
As discussed in the MP Hangout at 12/10/2019, please create a Milestone for MP 3.3 that includes Open API change for this release.

**Comment by arthurdm** [comment]
hi @ederks85 - can you please provide more details on this request?   Our next planned release is for MP OpenAPI 2.0, but that's not for another few months probably.

**Comment by kenfinnigan** [comment]
@arthurdm there needs to be, at a minimum, an OpenAPI 1.x release that includes https://github.com/eclipse/microprofile-open-api/issues/383 for the platform MP 3.3 release

**Comment by arthurdm** [comment]
thanks.  @kenfinnigan - when is the last possible date for us to release MP OpenAPI 2.0 in order to make it for MP 3.3?

**Comment by ederks85** [comment]
@arthurdm, per the MP Hangout minutes here linked below, the OpenAPI spec release should be complete between February 4th and 11th, 2020:

https://docs.google.com/document/d/16v3jVkcDzVz9BVU5aGEzPVbK-a8BIx7S1gbqToVUaLs/edit#heading=h.ex4zs92bf9kf

**Comment by arthurdm** [comment]
thanks @ederks85 

I am guessing since MP OpenAPI 2.0 will have breaking changes, it won't be able to go into MP 3.3?  It would need to wait for MP 4.0?

**Comment by ederks85** [comment]
@arthurdm correct:
- MP 3.3 needs OpenAPI 1.x to contain #383 as stated by @kenfinnigan 
- OpenAPI 2.0 with breaking changes can then be included in the next breaking change release (June/July 2020)

**Comment by arthurdm** [comment]
Thanks guys.  I've created the milestone: https://github.com/eclipse/microprofile-open-api/milestone/2    (fyi @EricWittmann)

**Comment by arthurdm** [comment]
Closing as we now have a milestone.
