### ISSUE TITLE
Release MP OpenAPI 1.2

### ISSUE THREAD

**Issue by arthurdm** [eclipse/microprofile-open-api#399]
In order to get the Jakarta EE 8 changes out for MicroProfile 3.0, we need to release MP OpenAPI 1.2.

**Comment by kenfinnigan** [comment]
In the MP Hangout today we came to the conclusion that we need to hold off on updating to Jakarta EE 8 until MP 4.0 in June, due to some dependency issues.

Details in a group post soon

**Comment by arthurdm** [comment]
thanks for letting us know @kenfinnigan

**Comment by arthurdm** [comment]
given the updated plans, in the hangout today we agreed to not release 1.2 and instead we'll just focus on releasing MP OpenAPI 2.0 to be included in MP 4.0.
