### ISSUE TITLE
Enable semantic versioning plugin to version packages 

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-open-api#406]
We need to semantic versioning packages correctly. Relying on eyeballing is not going to work. We need to get a tool to help us. I have done in the past for other spec but missed this one.

**Comment by jmini** [comment]
I am glad you are pushing this, I had the same idea back in the days when somebody reported on Gitter that some of my changes between `1.0` and `1.1` in mp-open-api were breaking changes. He told us only after the release.

---

In https://github.com/eclipse/microprofile-open-api/pull/407#issuecomment-591783894 I wrote my opinion about package versioning versus artefact versioning (the version in the maven coordinates).

I can't imagine that this is something that each spec needs to decide. How the bnd baseline plugin is used can't be decided at each individual spec level. This must be defined (as a guideline / good-practice) somewhere in the general project. Is there already an issue somewhere in the global MP project?

**Comment by jmini** [comment]
See also the related discussion on Google Group https://groups.google.com/g/microprofile/c/dzYrVG3g9XU
