### ISSUE TITLE
Remove 2.0 branch

### ISSUE THREAD

**Issue by EricWittmann** [eclipse/microprofile-open-api#408]
It seems we still have a stale `2.0` branch that we can probably remove.  There are two commits that haven't been merged to `master`.  We should see what those are before deleting `2.0`, but I think they're just ignore files or something else simple.

**Comment by MikeEdgar** [comment]
For reference, this relates to the following PRs, each with the same changes to `.gitignore`. The second commit to `2.0` is the PR itself.

[#369] Update gitignore to ignore IntelliJ IDEA files, merged to `1.x`
[#370] Update gitignore to ignore IntelliJ IDEA files, merged to `2.0`
[#371] Update gitignore to ignore IntelliJ IDEA files, merged to `master`

**Comment by arthurdm** [comment]
Agreed, and completed.
