### ISSUE TITLE
Specifying minimum/maximum for date/date-time

### ISSUE THREAD

**Issue by petrenyi-mark** [eclipse/microprofile-open-api#411]
We are using micoprofile openApi for generating an API description for our REST endpoints, and have a date type property on one of our request objects, which is required to be later than a specific date (2010-01-01 in our case), however if we set minimum to "2010-01-01" on @Schema we get a NumberFormatException.

We already realized that OpenApi specification itself is based on the JSON Schema draft which explicitly specifies minimum/maximum as number and does not have any other property for this (maybe there will be once with some vocabulary: https://github.com/json-schema-org/json-schema-spec/issues/116).

(Note: our dto-s are defined and validated by xsd-s, in which we can specify minimum for date ie.:

```
<xsd:simpleType name="RestrictedDateType">
        <xsd:restriction base="xsd:date">
            <xsd:minInclusive value="2010-01-01"/>
        </xsd:restriction>
</xsd:simpleType>
```

Our goal is to include this restriction in the openAPI definition as well.)

Do you have any suggestions (or workaround) to imply the given property has a minimum/maximum date in the API specification?

**Comment by EricWittmann** [comment]
Unfortunately I think the best you could do right now is to either add this as text in the description of the field (or in the bean) OR add an extension element.  But I do not believe there is support for min/max of dates in OpenAPI or JSON Schema.  You could try raising that as an issue in either or both of those communities.  Because it's not something supported there, we cannot support it in microprofile-openapi.

Is your goal to have the payloads actually validated using the OpenAPI schema, or is the schema just used for generating documentation?

**Comment by petrenyi-mark** [comment]
Thanks for the answer. I think we will add it to the description for now, since we're using the schema only for generating documentation.

**Comment by EricWittmann** [comment]
If you wanted to get fancy, you could annotate a field with an extension using the `@Extension` annotation.  And then implement your own custom filter to automatically update the description based on the value of the extension.  Something like:

```java
@Extension("x-minInclusive", "2010-01-01)
private Date myDateField;
```

Then your filter would look for the `x-minInclusive` property while filtering schemas.  Might not be worth the effort, but it would be cool. :)

**Comment by petrenyi-mark** [comment]
Thank you for the suggestion. Our objects are actually defined in xsd-s and we are using jaxb to generate the java objects. We have a plugin for jaxb which annotates the objects with `@Schema` based on the xsd definitions, so adding the restrictions to the description was simple. 
However, using the `@Extension` annotation would be more elegant, unfortunately as we tried to achieve this, we found that the smallrye implementation processes the annotation only if placed on the Resource class, we raised an issue for this: https://github.com/smallrye/smallrye-open-api/issues/267

**Comment by EricWittmann** [comment]
OK - sorry for making a suggestion that didn't work!  But at least we've identified a problem in SmallRye that we can fix!  

![image](https://user-images.githubusercontent.com/1890703/75247355-bc5f4c00-579f-11ea-937e-9d6d3bffd1f1.png)

**Comment by MikeEdgar** [comment]
Closing, as there is no further action to take from a MicroProfile OpenAPI perspective.
