### ISSUE TITLE
TCK bug? Use of equalTo PetStoreAppTest#testSchema rejects 10.0 for schema.multipleOf

### ISSUE THREAD

**Issue by tjquinno** [eclipse/microprofile-open-api#412]
In `PetStoreAppTest#testSchema`, line 58 retrieves `schema.multipleOf` and uses Hamcrest's `equalTo(10)` to check the value returned from the server under test.

The `Schema` annotation declares `multipleOf` as a `double`, and the `petId` parameter on  `PetResource#getPetById` is 10. 

The `Schema` model interface defines 'multipleOf' as a `BigDecimal`.  As it turns out the SnakeYAML serializer emits `10.0` in this case, using the `BigDecimal` type on the model interface to drive the output format. 

This causes the TCK test to fail -- incorrectly I think -- because the test uses Hamcrest's `equalTo(10)` which does not match `10.0`.

I have worked around this in the extensions we use with SnakeYAML so we can pass that TCK test, but it's a bit of a pain.

(There is a mention of the `double`/`BigDecimal` mismatch regarding `multipleOf` in #178 (closed) but that issue is really not directly related to this one.) 

Using decimal notation to format a `BigDecimal` seems perfectly reasonable, so can the test be changed to accept `10` and `10.0`? 

I have not looked for similar constructs elsewhere in the tests that might also need attention. This was the only test failure I saw due to this problem.

**Comment by tjquinno** [comment]
Related (I think), if the server replies with OpenAPI JSON that contain this as part of the schema data:

```
              "maximum": !!float '101',
              "minimum": !!float '9',
```
(with the explicit type tags) then the checks for `maximum` and `minimum` in the same `PetStoreAppTest#testSchema` test also fail.

Not surprisingly, if I inspect the `ValidatableResponse` response content using the debugger, then here is the JSON for those properties (I didn't pretty-format it -- it's copied and pasted directly from the debugger):
```
"maximum":101.0,"minimum":9.0
```
This seems to be triggering the same behavior I mentioned earlier with `multipleOf`.

**Comment by MikeEdgar** [comment]
Possible solution would be to update numeric equality checks with [`org.hamcrest.Matchers#comparesEqualTo`](http://hamcrest.org/JavaHamcrest/javadoc/1.3/org/hamcrest/Matchers.html#comparesEqualTo(T)) where appropriate.
