### ISSUE TITLE
Annotations for Map<K,V>

### ISSUE THREAD

**Issue by davidhervas** [eclipse/microprofile-open-api#415]
Hi,
I'm currently teaching myself how to develop some small REST WebServices with Quarkus.
I have been trying to document my API with microprofile-openapi-api-1.1.2.jar in order to display it on swagger and I have found a case where I don't find how to document.

`private final Map<String, List<MyClass>> myMap;`

I wanted to use the annotation @Schema to look something similar to :
`@Schema(name = "map", type = SchemaType.MAP, implementation = Map<String,List<MyClass>>.class)`

Is there any way to document a map with microprofile-open-api ?

Thanks by advance.
David.

**Comment by MikeEdgar** [comment]
Hi @davidhervas - what are you trying to generate for the output? Do you want to have the names of the allowed keys listed or do you only need to define the type as key/value pairs?

**Comment by davidhervas** [comment]
Hi @MikeEdgar, thanks for trying to help me.

My parameter is : `Map<String, List<MyClass>> myMap;`
I want to define the type as key/value pairs.
I want to provide a business description for the keys.
My class MyClass contains parameters with @org.eclipse.microprofile.openapi.annotations.media.Schema annotations and i want that information displayed on swagger.

I'm trying to generate an output like :
```
[ "businessKeyMap": [ {
                               parameter1 : String
                                            Example : "..."
                                            Pattern : "..."
                                            ...
                               parameter2
                               }]
]
```

Thanks.

**Comment by davidhervas** [comment]
The explanation in my previous post was confusing. Sorry.
I managed to get the result I want :

```
@Schema(name = "businessObjects", implementation = OpenApiBusinessObjects.class)
private final Map<String, List<MyObject>> businessObjects;
...
public class OpenApiBusinessObjects {

@Schema(name = "key", type = SchemaType.ARRAY, implementation = MyObject.class)
  List<MyObject> key;
}
...
public class MyObject {

  @Schema(example = "value")
  private String parameter1;
}
```

This generate the following output in swagger's schema :

```
businessObjects {
                   key [ {
                           parameter1  string
                                       example: value
}]
```
Note that the class OpenApiBusinessObjects only exist for OpenApi documentation.
