### ISSUE TITLE
Option to set the OpenAPI version

### ISSUE THREAD

**Issue by EricWittmann** [eclipse/microprofile-open-api#419]
This comes from someone on the Microprofile OpenAPI gitter chat room:

> 
> Franck Arnulfo
> @farnulfo_twitter
> Hi, is there anyway to have a "dynamic backport of OpenApi version" ?
> Context: we use Thorntail v2.6.0 which implement OpenAPI 3.0.1 so /openapi return a 3.0.1 document but our API Gateway (WSO2) only support 3.0.0 so we can't use the /openapi endpoint to configure the API.  We can manually import an OpenApi 3.0.0 by editing and modifying the dynamic 3.0.1 but I would like to avoid it.  So I was thinking about a way to have the /openapi endpoint to output a back version of the current one. Something like /openapi?version=3.0.0.

**Comment by MikeEdgar** [comment]
The `OASFilter` should support this, but a config property would be certainly be easier for developers.

**Comment by EricWittmann** [comment]
@MikeEdgar that's a good point.  It's also possible that you can set the openapi version in the static openapi file that you can include in your MP app.  I'll need to test that.  I suspect that it won't work but it's worth a try.

In any case, consensus on the call today is that this is not appropriate for the spec.  We'll address it in SmallRye though.
