### ISSUE TITLE
Wrong inheritance/polymorphism support ?

### ISSUE THREAD

**Issue by amoscatelli** [eclipse/microprofile-open-api#421]
In my JAX-RS resource Creable class extends Identifiable class

This is what is generated in the openapi file 

`    Identifiable:
      type: object
      properties:
        '@type':
          type: string
        id:
          type: string
        version:
          format: int64
          type: integer
     Creable:
      type: object
      properties:
        '@type':
          type: string
        id:
          type: string
        version:
          format: int64
          type: integer
        creation:
          format: date
          type: string`

Accoring to Openapi 3.0 documentation I expected this 

`    Identifiable:
      type: object
      properties:
        '@type':
          type: string
        id:
          type: string
        version:
          format: int64
          type: integer
     Creable:
      allOf:
        - $ref: "#/components/schemas/Identifiable"
        - type: object
      properties:
        creation:
          format: date
          type: string`

Why are the parent properties repeated by default ?

This is also a problem for polymorphism since this way a Creable isn't an Identifiable ...
So, for example, a service accepting an Identifiable as a parameter can't accept a Creable.

**Comment by MikeEdgar** [comment]
Hi @amoscatelli - this sounds like implementation-specific behavior. What server/runtime are you using? E.g. Quarkus, Open Liberty, etc.

**Comment by amoscatelli** [comment]
Yeah you are right, probably I should have posted this issue to Smallrye github ... I am using Wildfly 19. Anyway my expectations are right ?
