### ISSUE TITLE
Hide schema for specific HTTP method

### ISSUE THREAD

**Issue by Nicklas2751** [eclipse/microprofile-open-api#424]
It would be nice to be able to configure a list of HTTP methods for which a scheme is ignored. With this extension it would be possible to hide an ID field that is only used for updates (PUT, DELETE) but not needed for creation (POST).

In my case I have an object for which I have a REST api to perform CRUD.
This object has an ID field that is filled with an automatically generated value when it is created. So it's ok that the field appears in the schemas for PUT, GET and DELETE, but I don't want it in the schema for POST. So it would be cool if I could do something like that:
```java
@Schema(hiddenFor = {"POST"} )
private UUID id;
```

**Comment by EricWittmann** [comment]
After discussing this on the hangout today, this could be a very tricky thing to support.  It would really help if you could provide a more complete example of your expectations.  I definitely understand where you're coming from here, but it's not clear what you would expect to see in the generated OpenAPI file for something like this.  Can you elaborate, @Nicklas2751 ?

**Comment by Nicklas2751** [comment]
I created a example Project which shows my problem:
https://github.com/Nicklas2751/openapi-hidden-schema-example

You can run it by run `./mvnw clean install quarkus:dev`
When started you can download the generated openapi here:
http://0.0.0.0:8080/openapi
and swagger is located here: 
http://0.0.0.0:8080/swagger-ui

For POST it shows the user to fill the ID field as well. Specially the swagger-ui advices the user to set a ID. I want to generate the IDs so I don't want the user to fill the ID field for a new element. 

I am not a OpenAPI expert but I think something similar like this would be cool as part of the OpenAPI file:
```
      propertiesHiddenFor:
        id: post
```
The whole file is here: https://gist.github.com/Nicklas2751/ada3e97c63f6d07d61e7b3332545971e

With this it should be possible for applications like Swagger to ignore the id field for POST.

**Comment by MikeEdgar** [comment]
@Nicklas2751 - is it ever valid for someone to change the `id` when updating an existing record? If not, you could utilize the `readOnly` attribute for the `id` property.

**Comment by MikeEdgar** [comment]
@Nicklas2751, this issue was discussed in a recent MP OpenAPI call and given the limitations of OpenAPI/JSON schema itself on this feature, the suggestion is that this functionality can be achieved through other means such as type inheritance. For example, common properties would be listed in a base class/schema and those specific to particular operations like `GET` or `POST` would be placed in "sub-schemas" that reference the common schema (for example using `allOf`).

Please re-open this issue if you believe this merits additional discussion, etc.
