### ISSUE TITLE
Multiple openapi endpoints with multiple JAX-RS applications

### ISSUE THREAD

**Issue by Blubb324** [eclipse/microprofile-open-api#430]
Hello guys,

last time I was wondering about a deployment of 2 artefacts which are using open-api.

The server log said that only one open-api endpoint is possible. After googling around I have read this:

**"Before you proceed, note that the 1.0 version of the MicroProfile OpenAPI specification does not define how the /openapi endpoint may be partitioned in the event of multiple JAX-RS applications running on the same server. In other words, you must stick to one JAX-RS application per server instance as the behaviour for handling multiple applications is currently undefined."**

Source: https://github.com/OpenLiberty/guide-microprofile-openapi

Is there already a solution or a plan to specify this?

The current solution is that I have to deploy 1 artefact at 1 server. But e.g. there are 10 simple micro services it would be totally overhead to start 10 servers. Addionally I cannot combine them into 1 file, because of bounded contexts.

Btw. I really like openapi but at the moment this state is a bit impractical.

I hope it´s the right place for adressing this issue.
Thank you in advance!

**Comment by arthurdm** [comment]
hi @Blubb324 - you're right that the spec only specifies the behaviour of 1 application per server, which is considered a best practice in the microservice world.  

There are some vendors that have chosen to aggregate multiple OpenAPI docs (such as WebSphere Liberty), but when there are model conflicts the output may not be what you expected.  I believe it has been discussed before having a distinct OpenAPI endpoint for each app, but nothing concretely decided.

**Comment by Blubb324** [comment]
@arthurdm : Thank you for your answer. I will close this issue because it seems there is a similiar topic:

https://github.com/eclipse/microprofile/issues/168
