### ISSUE TITLE
[OAS 3.1.0] Update the checks for the openapi attribute

### ISSUE THREAD

**Issue by jmini** [eclipse/microprofile-open-api#434]
In order to support OpenAPI 3.1.0 (see #333) the `openapi` attribute must be `3.1.0`.

Example:

```yaml
---
openapi: 3.1.0
info:
  title: Example Specification
  version: "1.0"
servers:
- url: http://localhost:8000/
paths:
  /ping:
    get:
      operationId: ping
      responses:
        200:
          description: OK
```

**To be changed:**

The TCK checks for the value of the `openapi` attribute. This must be updated.

**Comment by benjamin-confino** [comment]
Comment to say I'm working on this
