### ISSUE TITLE
[OAS 3.1.0] Add summary to Info

### ISSUE THREAD

**Issue by jmini** [eclipse/microprofile-open-api#435]
In order to support OpenAPI 3.1.0 (see #333) we need to add `summary` to the info object

Reference: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#infoObject

Example
```yaml
openapi: 3.1.0
info:
  title: Example Specification
  summary: This is an example specification
  version: "1.0"
servers:
- url: http://localhost:8080/
paths:
  /ping:
    get:
      operationId: ping
      responses:
        200:
          description: OK
```

**To be added:**

* The model interface [Info.java](https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/models/info/Info.java): new methods (getter, setter, builder)
* The annotation definition [Info.java](https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/annotations/info/Info.java: new method
* TCK tests

**Comment by benjamin-confino** [comment]
Test comment
