### ISSUE TITLE
[OAS 3.1.0] Add identifier to License

### ISSUE THREAD

**Issue by jmini** [eclipse/microprofile-open-api#436]
In order to support OpenAPI 3.1.0 (see #333) we need to add `identifier` to the License object.

Reference: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#licenseObject

> An SPDX license expression for the API. The `identifier` field is mutually exclusive of the `url` field.

Example:

```yaml
openapi: 3.1.0
info:
  title: Example specification
  version: "1.0"
  license:
    name: Eclipse Public License 2.0
    identifier: EPL-2.0
servers:
- url: http://localhost:8080/
paths:
  /ping:
    get:
      operationId: ping
      responses:
        200:
          description: OK
```

**To be added:**

* The model interface [License.java](https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/models/info/License.java): new methods (getter, setter, builder)
* The annotation definition [License.java](https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/annotations/info/License.java): new method
* TCK tests

As previously discussed (#339 or #331), it is not the role of the MicroProfile OpenAPI to add checks to ensure that `identifier` and `url` can not be set simultaneously. This is up to the vendor.

**Comment by benjamin-confino** [comment]
Please assign this one to me
