### ISSUE TITLE
Rework on Release note on 2.0

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-open-api#441]
Since you are releasing 2.0 version, what breaking changes have you introduced and some migration suggestions. You need to follow [this](https://wiki.eclipse.org/MicroProfile/ReleaseNotes) instruction.

**Comment by jmini** [comment]
See the list in issue #251.

I could not find the expected format in the linked instructions.

**Comment by jmini** [comment]
@Emily-Jiang on Gitter:

> The release note for 2.0 should be developer focus. For MP Open API 1.x, what breaking changes are there from api change, behaviour change, etc. If there is workaround to go back to the previous behaviour, you should mention it there

Is your concern that we should add more details?

**Example:**

When we write:

https://github.com/eclipse/microprofile-open-api/blob/3cae33ad2a2dd0e3cbe124b0f304e4848cb299e5/spec/src/main/asciidoc/release_notes.asciidoc#L65

Is this good enough or should we add the complete list of methods that were renamed?

Same for:

https://github.com/eclipse/microprofile-open-api/blob/3cae33ad2a2dd0e3cbe124b0f304e4848cb299e5/spec/src/main/asciidoc/release_notes.asciidoc#L67

We should try to explain how this impacts the end-developers?

**Comment by Emily-Jiang** [comment]
@jmini You need to list what methods were renamed or removed. You also need to mention what model interface. If I directly use the apis, when I see this, I will know whether I am impacted or not.

**Comment by Emily-Jiang** [comment]
@jmini in your release note you did not mention the newly added section 7 about the platform open api.

**Comment by jmini** [comment]
@Emily-Jiang : I do not follow… sorry.

I started something with more details about the removed methods and interfaces.

Probably we can discuss directly on the PR when it is ready.

**Comment by Emily-Jiang** [comment]
@jmini which bit you don't follow? The new section 7 was introduced in MP open API but it was not mentioned in the release. Are the issues listed in the milestone for MP Open API 2.0?

**Comment by Emily-Jiang** [comment]
@jmini @arthurdm in 2.0 Release note, a new section `Incompatible Changes` should be added to mention all of the items under https://github.com/eclipse/microprofile-open-api/issues/251
