### ISSUE TITLE
Schema property: additionalProperties is Missing

### ISSUE THREAD

**Issue by oberstrike** [eclipse/microprofile-open-api#451]
Hi, guys,

I found out that the attribute "additionalProperties" is missing in the schema annotation.
This should be included soon, as it is a possible vulnerability.

**Comment by MikeEdgar** [comment]
This looks like a duplicate of #423.

**Comment by oberstrike** [comment]
Thats true. Thanks!

**Comment by MikeEdgar** [comment]
Closing duplicate of #423
