### ISSUE TITLE
SmallRye: Compatible Certification Request for MicroProfile OpenAPI 2.0

### ISSUE THREAD

**Issue by phillip-kruger** [eclipse/microprofile-open-api#459]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  [Red Hat](https://www.redhat.com/en)

- [x] Product Name, Version and download URL (if applicable):<br/>
  [SmallRye OpenAPI 2.1.0-RC1](https://search.maven.org/artifact/io.smallrye/smallrye-open-api/2.1.0-RC1/pom)

- [x] Specification Name, Version and download URL:<br/>
   [MicroProfile OpenAPI 2.0](https://search.maven.org/artifact/org.eclipse.microprofile.openapi/microprofile-openapi-spec/2.0/pom)

- [x] Public URL of TCK Results Summary:<br/>
  https://github.com/smallrye/smallrye-open-api/actions/runs/410912721 <br/>

- [x] Java runtime used to run the implementation:<br/>
  Java 8 and 11 

- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  GH Actions - Ubuntu

- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).

- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by kwsutter** [comment]
The Specification Name and Version item should point at the actual Spec. I would put a reference to the eventual maven repo: https://search.maven.org/artifact/org.eclipse.microprofile.openapi/microprofile-openapi-spec/2.0/pom

Same thing for the Compatible Impl. Reference the maven artifact: https://search.maven.org/artifact/io.smallrye/smallrye-openapi/2.1.0-RC1/jar or have the binary available in a download directory that will not be removed.  We need a "permanent" location for the CI.

**Comment by radcortez** [comment]
Updated the links. 

The version alignment is just a coincidence :)

**Comment by dblevins** [comment]
These public TCK results are not consumer-friendly and I think we want to do much better in future releases.

Here's the most ideal setup:

 -  The results summary should be visible on the page itself, not inside a zip.  If there are multiple JDKs listed, there is a summary for each one.
 -  The specification/TCK name and version should be on the same page
 -  The product name, version and where to download should be on the page.

The page also must be permanent.  This looks like output from a CI run still in the CI system and it isn't clear if old builds eventually get removed.

We don't need to fix all of this now, but we should plan to improve things in this area for future releases.

**Comment by MikeEdgar** [comment]
Completed
