### ISSUE TITLE
Remove ArraySchema annotation 

### ISSUE THREAD

**Issue by arturdzm** [eclipse/microprofile-open-api#46]
Remove ArraySchema annotation and reference to it.
AllOff, oneOf and other schema properties use Java class for definition.
We should keep that consistent with array schemas as well
Usage difference:
Instead of using array=@ArraySchema(schema=@Schema)

For simple types:
`@Schema(type="array", implementation=String.class)`

For complex types:

```
@Schema("customize Todo schema" )
public class Todo {

}

@Schema(type="array", customize array schema, implementation=Todo.class)
```

**Comment by arthurdm** [comment]
Fixed by PR #89
