### ISSUE TITLE
SmallRye Compatible Certification Request for MicroProfile OpenAPI 1.2

### ISSUE THREAD

**Issue by phillip-kruger** [eclipse/microprofile-open-api#476]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  [Red Hat](https://www.redhat.com/en)

- [x] Product Name, Version and download URL (if applicable):<br/>
  [SmallRye OpenAPI 2.0.25](https://repo1.maven.org/maven2/io/smallrye/smallrye-open-api-parent/2.0.25/)
                                               
- [x] Specification Name, Version and download URL:<br/>
  MicroProfile OpenAPI 1.2

- [x] Public URL of TCK Results Summary:<br/>
  https://github.com/smallrye/smallrye-open-api/actions/runs/636763543

- [x] Java runtime used to run the implementation:<br/>
  Java 8 and 11

- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  GH Actions - Ubuntu  

- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by MikeEdgar** [comment]
Completed
