### ISSUE TITLE
Parameters in Link model should be of type Map<String, Object>

### ISSUE THREAD

**Issue by arturdzm** [eclipse/microprofile-open-api#50]
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#linkObject
parameters filed is Map[string, Any | {expression}]

So we should switch to Object for consistency with rest of the models.

**Comment by arthurdm** [comment]
Fixed by https://github.com/eclipse/microprofile-open-api/pull/59.  Thanks!
