### ISSUE TITLE
Code formatting rules are unsuitable

### ISSUE THREAD

**Issue by Azquelt** [eclipse/microprofile-open-api#518]
The formatting rules that are currently used on this project make the code completely unreadable. See this line for an example: [JAXRSApp.java#L66][bad-line].

I think the major problem is that line breaks aren't allowed after a comma separating annotation parameters.

I realise the formatting rules are inherited from the parent microprofile project, but can we either get the parent copy updated or tweak them for this project which by design allows for very large annotations?

[bad-line]: https://github.com/eclipse/microprofile-open-api/blob/685c4072b099cadaa80d0ef060cc8a67e34859a1/tck/src/main/java/org/eclipse/microprofile/openapi/apps/airlines/JAXRSApp.java#L66

**Comment by MikeEdgar** [comment]
@Azquelt, I think we can consider this done with #537. Do you agree or do you think there's room for further improvement?

**Comment by Azquelt** [comment]
Good point, yes I think the formatting rules are ok now. We can close this but you've reminded me that I meant to open an issue to push the changes upstream.
