### ISSUE TITLE
Improve model by adding enums to place such Parameter.in, or SecurityScheme.type

### ISSUE THREAD

**Issue by arturdzm** [eclipse/microprofile-open-api#52]
Instead of using String add enums to improve user experience and chance of usage errors

**Comment by arthurdm** [comment]
Merge https://github.com/eclipse/microprofile-open-api/pull/59 delivered the fix for Parameter.in, but leaving this issue open to address the SecurityScheme.type part.

**Comment by arthurdm** [comment]
Actually - SecurityScheme.type is already in.  Closing this issue.
