### ISSUE TITLE
Kotlin value classes not represented correctly.

### ISSUE THREAD

**Issue by dirkbolte** [eclipse/microprofile-open-api#544]
When adding a kotlind value class to a response, the property name is added twice. I tried different approaches with specifying schema, but wasn't able to correct or hide the additional property.

value class:

```kotlin
@JvmInline
value class IdWithOverwrittenSchema(val value: Long)
```

Response:

```kotlin
data class TestResponse(
    @field:Schema(type = SchemaType.INTEGER, implementation = Long::class, name = "idWithOverwrittenSchema")
)
```

Resource:

```kotlin
@Path("/test")
class TestResource {
    @GET
    fun testMethod(): TestResponse {
        return TestResponse()
    }
}
```

I tried different variations and put some of them in a sample project: https://github.com/dirkbolte/openapi-test

The result looks like this:
<img width="751" alt="value_class_bug" src="https://user-images.githubusercontent.com/1572945/180978375-964539f8-45c1-4b92-abd0-ca4d156b6a6a.png">

value classes as method parameters (e.g. on `@GET` with `@PathParam` do not have this issue and are parsed correctly.

Versions:
- microprofile-openapi-api: 2.0.1
- Quarkus (incl. resteasy): 2.10.3.Final
- Java: 11
- Kotlin: 1.6.21

**Comment by phillip-kruger** [comment]
Rather open an issue in Quarkus, or maybe even Smallrye openapi.

**Comment by dirkbolte** [comment]
done: https://github.com/smallrye/smallrye-open-api/issues/1195
