### ISSUE TITLE
Question on multiple OpenAPI definitions

### ISSUE THREAD

**Issue by aerfus** [eclipse/microprofile-open-api#555]
Hello,

is there a way to defined multiple OpenAPI definitions, so in UI you will have a combobox to display selected definition only?

See https://quarkus.io/blog/stylish-api/#other-swagger-ui-options as an example.

Thank you in advance!

**Comment by MikeEdgar** [comment]
MicroProfile OpenAPI supports generating one definition per application, but you could still reference an external definition using the configurations from your link (assuming you're using Quarkus).

**Comment by aerfus** [comment]
Hi MikeEdgar,

thank you for the answer.
Still, is it possible to hide certain tags in the generated definition?

**Comment by MikeEdgar** [comment]
@aerfus , you can look at using the following properties to exclude packages or classes
- `mp.openapi.scan.exclude.packages`
- `mp.openapi.scan.exclude.classes`

If you need to exclude operations/methods you will probably need to implement an `OASFilter`, configured with `mp.openapi.filter`.
