### ISSUE TITLE
MP Parent version deviates from MP Parent TCK BOM version

### ISSUE THREAD

**Issue by JanWesterkamp-iJUG** [eclipse/microprofile-open-api#573]
The MP Parent was updated from 2.6 to 2.7, but the tck-bom version is untouched at 2.6.
These versions should be in sync.

Meanwhile, both versions are outdated, the current 2.x version is 2.8.

In gerneral, when updating the MP Parent version, the propery https://github.com/eclipse/microprofile-open-api/blob/0649b7f6d299a33c58fef56e19e17786227a0560/pom.xml#L43[version.microprofile.tck.bom] should be updated to the same value.
BTW, the property name deviates from Maven naming conventions, so renaming this property to **microprofile.tck.bom.version** would make sense too.

**Comment by Azquelt** [comment]
Yeah, we should pick up the newer version of the tck-bom and parent before the next release.

**Comment by Emily-Jiang** [comment]
Please reevaluate this fix and align with [this](https://groups.google.com/g/microprofile/c/2ZiZt_gs6Zc) discussion. fyi @MikeEdgar @Azquelt

**Comment by MikeEdgar** [comment]
@Emily-Jiang I think we are in good shape. The linked PR #577 simply updates the parent POM and adds `module-info` (since we're now building for Java 11). The other relevant PR #580 (issue #574) changes "JAX-RS" to "Jakarta REST" in the spec text and JavaDocs.

Let me know if I've missed something.
