### ISSUE TITLE
[OAS 3.1.0] New Parameter style values valid for object type

### ISSUE THREAD

**Issue by Azquelt** [eclipse/microprofile-open-api#586]
The [Parameter.style](https://spec.openapis.org/oas/v3.1.0.html#style-values) field specifies the way a parameter is passed. The `spaceDelimited` and `pipeDelimited` values are now valid when `Parameter.type` is `object`.

We may want to:
- Update relevant documentation if we have any
- Add a test which builds a model with these values to ensure they're permitted

**Comment by Azquelt** [comment]
I don't see any documentation restricting the value of `style`, so we just need the new test for this issue.

**Comment by benjamin-confino** [comment]
Please assign this to me
