### ISSUE TITLE
[OAS 3.1.0] Operation.requestBody now permitted for HTTP methods which don't allow a request body

### ISSUE THREAD

**Issue by Azquelt** [eclipse/microprofile-open-api#591]
[Operation.requestBody](https://spec.openapis.org/oas/v3.1.0.html#fixed-fields-7) now allows a body to be provided even if the HTTP method of the operation doesn't support it (e.g. `GET`).

We may want to:
- Update any relevant documentation
- Add a test for a `GET`, `HEAD` and `DELETE` operations with a request body specified

**Comment by Azquelt** [comment]
Can't see anywhere that we document the old restriction, so this just needs a new test.

**Comment by benjamin-confino** [comment]
Please assign this to me.
