### ISSUE TITLE
[OAS 3.1.0] Only one of Paths, Components, or Webhooks is required

### ISSUE THREAD

**Issue by Azquelt** [eclipse/microprofile-open-api#592]
Previously `paths` was always required in an OpenAPI document, but now only one of `paths`, `components` and `webhooks` is required.

In practise, I suspect that usually we will almost always have paths when using MP OpenAPI.

However, we may want to:
- Check and update our documentation in this area
- Add a test building a model without a `paths` entry

**Comment by Azquelt** [comment]
I can't see anywhere we're requiring `paths`, so we just need a test where we build a model without `paths`. This would need to be a separate app and it should probably disable scanning and just build the model with `OASModelReader`.

**Comment by benjamin-confino** [comment]
Please assign this to me.
