### ISSUE TITLE
TCK Annotation coverage

### ISSUE THREAD

**Issue by arthurdm** [eclipse/microprofile-open-api#60]
Our TCK will have 2 core input applications:  Airlines (issue #61) and PetStore (issue #64)

This issue will track the investigation of TCK coverage for each OpenAPI annotation.

So for each of the annotations in the list below:

- check the box of the ones you want to work on 
- put a comment saying you're working on Annotation x, y and z. 
- investigate if the annotation usage in our sample apps cover the corresponding OpenAPI element from the spec (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md)
-  If not, then either update the current usage or create a new resource/class within the app that makes use of that annotations, and then update the expected output of the TCK.

If you're wondering what kind of coverage a particular annotation could have, here are 2 repositories that contain many of the same annotations (just different packages).  Search for tests and samples that use them:
- https://github.com/swagger-api/swagger-samples/tree/2.0
- https://github.com/swagger-api/swagger-core/tree/2.0/modules

Annotation list:

- [x] Callback
- [x] Callbacks
- [x] Components
- [x] Explode
- [x] ParameterIn
- [x] ParameterStyle
- [x] SecuritySchemeIn
- [x] SecuritySchemeType
- [x] Extension
- [x] Extensions
- [x] ExternalDocumentation
- [x] Header
- [x] Contact
- [x] Info
- [x] License
- [x] Link
- [x] LinkParameter
- [x] ArraySchema
- [x] Content
- [x] DiscriminatorMapping
- [x] Encoding
- [x] ExampleObject
- [x] Schema
- [x] OpenAPIDefinition
- [x] Operation
- [x] Parameter
- [x] Parameters
- [x] RequestBody
- [x] APIResponse
- [x] APIResponses
- [x] OAuthFlow
- [x] OAuthFlows
- [x] OAuthScope
- [x] SecurityRequirement
- [x] SecurityRequirements
- [x] SecurityScheme
- [x] SecuritySchemes
- [x] Server
- [x] Servers
- [x] ServerVariable
- [x] Tag
- [x] Tags

**Comment by leochr** [comment]
Not able to check the box.

I'll look into the following annotations:

APIResponse
APIResponses
Tag
Tags
Header
Components
OpenAPIDefinition
Contact
Info
License

**Comment by janamanoharan** [comment]
I will do:
- [ ] Parameter
- [ ] Parameters
- [ ] RequestBody
- [ ] Operation
- [ ]  Server
- [ ] Servers
- [ ] ServerVariable

**Comment by turkeylurkey** [comment]
I'll look at

Schema
ArrayScema
DiscriminatorMapping
Encoding

**Comment by a-saf** [comment]
I'll be working on:

[ ] OAuthFlow
[ ] OAuthFlows
[ ] OAuthScope
[ ] SecurityRequirement
[ ] SecurityRequirements
[ ] SecurityScheme
[ ] SecuritySchemes
[ ] ParameterIn
[ ] ParameterStyle
[ ] SecuritySchemeIn
[ ] SecuritySchemeType
ParameterStyle
SecuritySchemeIn
SecuritySchemeType

**Comment by arthurdm** [comment]
thanks everyone!  I updated the checkboxes.  Only Explode and Content left.

**Comment by turkeylurkey** [comment]
I'm working on Content.

Explode is part of Parameter.

**Comment by a-saf** [comment]
Just a note: won't be doing ParameterIn and ParameterStyle, because they are part of Parameter, so they should be covered along with that annotation.

**Comment by leochr** [comment]
@a-saf @janamanoharan @turkeylurkey 
For the annotation you've picked up, please ensure all **attributes** of those annotations are used within either the airlines or petstore app by checking the references to them (in case you are not sure how to do that, in eclipse, select annotation/methods and do either command+shift+G or right click and References->Workspace). Some of the annotations are being worked, but when I did some random checking, some attributes are not used anywhere in the apps (e.g. SecurityScheme.ref()). If the attribute has a default value, then specify a non-default value (for enums especially).

**Comment by leochr** [comment]
FYI, If you'll be modifying the airlines app, then there are bunch of referenceable items (from #/components) within org.eclipse.microprofile.openapi.apps.airlines.JAXRSApp (within Components inside of OpenAPIDefinition)

**Comment by arthurdm** [comment]
Closing this one via the various PRs that were contributed (see them above).
