### ISSUE TITLE
[OAS 3.1.0] Update spec document references

### ISSUE THREAD

**Issue by Azquelt** [eclipse/microprofile-open-api#606]
Most places that the spec document talks about OpenAPI v3, it should be updated to reference version 3.1.0.

Any links in the spec document also need to be updated.

**Comment by benjamin-confino** [comment]
You can assign this one to me

**Comment by Azquelt** [comment]
Please refer to https://spec.openapis.org/oas/v3.1.0.html for the correct name of anything and link within that document where our spec needs to link to the OpenAPI spec.
