### ISSUE TITLE
Port airlines application into TCK

### ISSUE THREAD

**Issue by arthurdm** [eclipse/microprofile-open-api#61]
Porting airlines app (https://github.com/microservices-api/oas3-airlines) to use MicroProfile OpenAPI and to live inside the TCK.  

Needs to be able to run via the TCK.

**Comment by a-saf** [comment]
I'm currently working on this issue

**Comment by arthurdm** [comment]
Application code merged via merge #64. Now we just need to hook that up to the TCK so that it runs against a vendor's impl.

**Comment by arthurdm** [comment]
@navidsh - will you be looking into hooking this app into the TCK?

**Comment by navidsh** [comment]
@arthurdm I'm working on this issue now.

**Comment by arthurdm** [comment]
Closing this via PR #110
