### ISSUE TITLE
Port PetStore app into TCK

### ISSUE THREAD

**Issue by arthurdm** [eclipse/microprofile-open-api#62]
Similar to issue #61 we will need to port the PetStore app into the TCK (using MP OpenAPI annotations instead of Swagger annotations).

We should grab the best sample from within this repo: https://github.com/swagger-api/swagger-samples/tree/2.0/java

**Comment by a-saf** [comment]
I'll be taking a look into this

**Comment by arthurdm** [comment]
Closing with merge #76.  Thanks @a-saf !
