### ISSUE TITLE
TCK test for OASFilter

### ISSUE THREAD

**Issue by arthurdm** [eclipse/microprofile-open-api#66]
We need a set of tests for the OASFilter API.  For simplicity, configure it using META-INF/microprofile-config.properties.

We'll need to change the expected output accordingly.

**Comment by leochr** [comment]
@arthurdm I'll work on this one.

**Comment by leochr** [comment]
TCK tests for filter were delivered by these pull requests: #158 #160

**Comment by arthurdm** [comment]
Thanks @leochr
