### ISSUE TITLE
Several TCK test cases require header `style` set to default value `simple`

### ISSUE THREAD

**Issue by MikeEdgar** [eclipse/microprofile-open-api#661]
There are several TCK test cases that require a header's `style` value is set to `simple`, which is the OAS default for headers [1]. Given that it is the default and is even omitted from the OAS spec examples, it appears this check should be removed from these tests.

A few examples:
- [org.eclipse.microprofile.openapi.tck.FilterTest.testFilterHeader(String)](https://github.com/eclipse/microprofile-open-api/blob/112b7b16806982223d638f415d2979beaf89f6a8/tck/src/main/java/org/eclipse/microprofile/openapi/tck/FilterTest.java#L164)
- [org.eclipse.microprofile.openapi.tck.AirlinesAppTest.testHeaderInAPIResponse(String)](https://github.com/eclipse/microprofile-open-api/blob/112b7b16806982223d638f415d2979beaf89f6a8/tck/src/main/java/org/eclipse/microprofile/openapi/tck/AirlinesAppTest.java#L933)
- [org.eclipse.microprofile.openapi.tck.AirlinesAppTest.testHeaderInComponents(String)](https://github.com/eclipse/microprofile-open-api/blob/112b7b16806982223d638f415d2979beaf89f6a8/tck/src/main/java/org/eclipse/microprofile/openapi/tck/AirlinesAppTest.java#L991)
- [org.eclipse.microprofile.openapi.tck.AirlinesAppTest.testHeaderInEncoding(String)](https://github.com/eclipse/microprofile-open-api/blob/112b7b16806982223d638f415d2979beaf89f6a8/tck/src/main/java/org/eclipse/microprofile/openapi/tck/AirlinesAppTest.java#L958)

[1] https://spec.openapis.org/oas/v3.0.3.html#parameterStyle

**Comment by Azquelt** [comment]
I agree, we should change these checks to be either equal to `simple` or absent.

**Comment by Azquelt** [comment]
I found some other cases where we require `style` to be present with its default value:

Parameters:
- [AirlinesAppTest.testBookingIdMethods](https://github.com/eclipse/microprofile-open-api/blob/112b7b16806982223d638f415d2979beaf89f6a8/tck/src/main/java/org/eclipse/microprofile/openapi/tck/AirlinesAppTest.java#L411)

Encoding objects ([style is like a query parameter](https://spec.openapis.org/oas/v3.0.3.html#fixed-fields-12), with default value `form`):
- [AirlinesAppTest.testEncodingRequestBody](https://github.com/eclipse/microprofile-open-api/blob/112b7b16806982223d638f415d2979beaf89f6a8/tck/src/main/java/org/eclipse/microprofile/openapi/tck/AirlinesAppTest.java#L693)
- [AirlinesAppTest.testEncodingResponses](https://github.com/eclipse/microprofile-open-api/blob/112b7b16806982223d638f415d2979beaf89f6a8/tck/src/main/java/org/eclipse/microprofile/openapi/tck/AirlinesAppTest.java#L705)
