### ISSUE TITLE
Build fails with static OpenAPI file in META-INF folder

### ISSUE THREAD

**Issue by dhoffer** [eclipse/microprofile-open-api#669]
This was previously posted in https://github.com/quarkusio/quarkus/issues/43940 but its really and openapi issue so posting here as well.

When we put a static OpenAPI file in META-INF folder (the default location), the build fails with this error:

C:\projects\acctmgt-back\target\acctmgmt-back.jar -> C:\projects\acctmgt-back\target\acctmgmt-back.jar.original: The process cannot access the file because it is being used by another process.

If we remove the static OpenAPI file then the build is successful.

So apparently Quarkus has a file lock on this file.

We are using 999-SNAPSHOT to pickup some other recent changes.

Note we are building on Windows and generating an uber-jar type.

**Comment by MikeEdgar** [comment]
@dhoffer this repository is for the MicroProfile specification, which defines the OpenAPI Java interfaces and configuration properties that an implementation uses. The Quarkus issue you referenced is the correct place to report it since it's dealing with the Quarkus implementation.

**Comment by dhoffer** [comment]
@MikeEdgar Oh, okay I wasn't sure where was the right place as I thought this might be internally handled by the MicroProfile library.
