### ISSUE TITLE
TCK tests for static files

### ISSUE THREAD

**Issue by arthurdm** [eclipse/microprofile-open-api#67]
We need a new set of tests for using static (pre-generated) files in META-INF/openapi.

There should be tests where the file is complete (ie: with annotation support turned off), as well as hybrid tests where the static file is supplemented by either the OASModelReader or annotations.

**Comment by mrglavas** [comment]
I am working on assertions for the static file.

**Comment by arthurdm** [comment]
Thanks to everyone who contributed to this.
