### ISSUE TITLE
Property quarkus.smallrye-openapi.always-run-filter = true does not work

### ISSUE THREAD

**Issue by dhoffer** [eclipse/microprofile-open-api#670]
According to this link  https://quarkus.io/guides/openapi-swaggerui#runtime-filters, it says that this property should cause the 

quarkus.smallrye-openapi.always-run-filter = true filters to run on every request but it does not work.  The filters only get called when the OpenAPI document is first requested.

We need the filters to run on each request as we need to customize the response based on the user's permissions which is in the Headers of the request so how can we get the above to work?

Also this is part 2 of this request.  What we really need to do is do two rounds of filtering. (for performance reasons).

Round 1 of filtering is generic and takes a long time so just want to do this once when the application starts (e.g. prior to first request).
Round 2 of filter would be much lighter and fast as it just hides some OpenAPI items based on the current user's permissions.

We would be happy to just get the first part working and then enhance with round 2 later.

**Comment by MikeEdgar** [comment]
@dhoffer, similar to the other issue, this is indeed a Quarkus issue and not a specification issue. Please open an issue there and I will review further. Also, attaching a reproducer (small application to demo the problem) is always helpful to speed up review and fix.

**Comment by MikeEdgar** [comment]
Related Quarkus issue: https://github.com/quarkusio/quarkus/issues/44046

**Comment by dhoffer** [comment]
@MikeEdgar Agreed, this is a Quarkus property that is not working.

**Comment by dhoffer** [comment]
@MikeEdgar I did just create a small app as reproducer but the flag did work in that case and the filter ran on every request.  But it does not in our large app.  No idea why.  If you have any clues as what might cause this to fail, let me know.  I'll keep working on a reproducer where it fails.
