### ISSUE TITLE
microprofile-open-api does not read user properties correctly/consistently

### ISSUE THREAD

**Issue by dhoffer** [eclipse/microprofile-open-api#671]
We have several REST services hidden as they are not user facing REST endpoints.  We have been adding them to our application.yml file but certain properties can't be read from that file.  The ones that can be read this way include mp.openapi.extensions.smallrye.XXX.  The ones that can't be read this way include mp.openapi.scan.exclude.XXX. 

We found that the only way to read the latter ones is to include them in the microprofile-config.properties file.  This is undesirable for two reasons.  Properties can't be specified in just one file, and microprofile-config.properties requires them in CSV list which is very hard to read.

Also what we would really like is an class level annotation to do the same.  Originally I thought @Schema(hidden = true) would work but it doesn't work at the class level.

Upon further investigation it appears the problem is that it can't read the properties that are Lists in YAML files.  If we put the CSV string in the YAML file then it can read it.  But it should be able to read lists in YAML format in YAML files.

**Comment by Azquelt** [comment]
This repository is for the MicroProfile OpenAPI specification and API and doesn't deal with issues with any particular implementation.

Please raise your issue against the implementation or runtime that you're using, either [smallrye-open-api](https://github.com/smallrye/smallrye-open-api/) if you're using that directly, or the runtime that includes it, e.g. quarkus.

**Comment by dhoffer** [comment]
Okay I created new one https://github.com/smallrye/smallrye-open-api/issues/2046
