### ISSUE TITLE
TCK tests for openapi endpoint

### ISSUE THREAD

**Issue by arthurdm** [eclipse/microprofile-open-api#69]
We will be using the `/openapi` endpoint for most of our TCK tests already, but this issue will track the inclusion of specific endpoint tests that will use different `Accept` headers for json and yaml.

**Comment by navidsh** [comment]
@mrglavas, @turkeylurkey and I are working on this.

**Comment by mrglavas** [comment]
We'll want to write assertions which cover each of the annotations. I've copied the checklist below.
Annotation list:
- [ ] Callback
- [ ] Callbacks
- [ ] Components
- [ ] Explode
- [ ] ParameterIn
- [ ] ParameterStyle
- [ ] SecuritySchemeIn
- [ ] SecuritySchemeType
- [ ] Extension
- [ ] Extensions
- [ ] ExternalDocumentation
- [ ] Header
- [ ] Contact
- [ ] Info
- [ ] License
- [ ] Link
- [ ] LinkParameter
- [ ] ArraySchema
- [ ] Content
- [ ] DiscriminatorMapping
- [ ] Encoding
- [ ] ExampleObject
- [ ] Schema
- [ ] OpenAPIDefinition
- [ ] Operation
- [ ] Parameter
- [ ] Parameters
- [ ] RequestBody
- [ ] APIResponse
- [ ] APIResponses
- [ ] OAuthFlow
- [ ] OAuthFlows
- [ ] OAuthScope
- [ ] SecurityRequirement
- [ ] SecurityRequirements
- [ ] SecurityScheme
- [ ] SecuritySchemes
- [ ] Server
- [ ] Servers
- [ ] ServerVariable
- [ ] Tag
- [ ] Tags

**Comment by mrglavas** [comment]
Going to start with the Info, Contact and License annotations.

**Comment by leochr** [comment]
I am covering Component, Tag, Tags and Header.

**Comment by turkeylurkey** [comment]
Starting with Schema

**Comment by janamanoharan** [comment]
doing 
- [ ] Operation

**Comment by navidsh** [comment]
I'm covering the following annotations:
- ExternalDocumentation
- Server
- Servers
- ServerVariable

**Comment by a-saf** [comment]
I'll do SecurityScheme and SecurityRequirement

**Comment by arthurdm** [comment]
thanks everyone. I updated the checkboxes based on the comments.

**Comment by mrglavas** [comment]
I'm now working on Operation.

**Comment by a-saf** [comment]
I'm working on Link, Encoding

**Comment by arthurdm** [comment]
updated checkboxes

**Comment by turkeylurkey** [comment]
I'll handle Extension, Extensions, Example Object

**Comment by arthurdm** [comment]
updated

**Comment by a-saf** [comment]
Also doing OAuthFlow, OAuthFlows, OAuthScope, as these relate to SecurityScheme (confirmed this with Jana @janamanoharan).
@arthurdm Also completed LinkParameter, and SecuritySchemeIn/SecuritySchemeType (these are enums for SecurityScheme annotation)

**Comment by leochr** [comment]
I am working on Content

**Comment by turkeylurkey** [comment]
I am working on DiscriminatorMapping

**Comment by arthurdm** [comment]
All done - thanks everyone!
